// C1 レベルの初期単語セット（動作確認用）。
// t: 見出し語 / k: 種類 (word|idiom|phrase) / c: カテゴリ (daily|biz|it) / lv: 難易度 1-3
// ja: 意味 / ex: 例文 / m: 例文中で強調する部分 / exJa: 例文和訳 / hl: 和訳中の該当部分
// alt: 和訳→英語で正解として認める別表記
export const CATEGORIES = { daily: '日常会話', biz: 'ビジネス', it: 'IT' };
export const KINDS = { word: '単語', idiom: '熟語', phrase: 'フレーズ' };

export const WORDS = [
  // ---- IT ----
  { id: 'leverage', t: 'leverage', k: 'word', c: 'it', lv: 1, ja: '（資源などを）活用する',
    ex: 'We can leverage our existing infrastructure to cut costs.', m: 'leverage',
    exJa: '既存のインフラを活用してコストを削減できる。', hl: '活用して' },
  { id: 'scalable', t: 'scalable', k: 'word', c: 'it', lv: 1, ja: '拡張性のある、規模を拡大できる',
    ex: 'We need a scalable architecture that can handle ten times the current traffic.', m: 'scalable',
    exJa: '現在の10倍のトラフィックに対応できる拡張性のあるアーキテクチャが必要だ。', hl: '拡張性のある' },
  { id: 'deprecate', t: 'deprecate', k: 'word', c: 'it', lv: 2, ja: '（機能などを）非推奨にする',
    ex: 'This API endpoint will be deprecated in the next release.', m: 'deprecated',
    exJa: 'このAPIエンドポイントは次のリリースで非推奨になる。', hl: '非推奨になる' },
  { id: 'mitigate', t: 'mitigate', k: 'word', c: 'it', lv: 2, ja: '（影響・リスクを）軽減する',
    ex: 'We rolled back the deployment to mitigate the impact on users.', m: 'mitigate',
    exJa: 'ユーザーへの影響を軽減するためにデプロイをロールバックした。', hl: '軽減する' },
  { id: 'backward-compatible', t: 'backward compatible', k: 'phrase', c: 'it', lv: 2, ja: '後方互換性のある',
    ex: 'The new version is fully backward compatible with existing plugins.', m: 'backward compatible',
    exJa: '新バージョンは既存のプラグインと完全に後方互換性がある。', hl: '後方互換性がある', alt: ['backwards compatible'] },
  { id: 'technical-debt', t: 'technical debt', k: 'phrase', c: 'it', lv: 1, ja: '技術的負債',
    ex: 'We need to allocate time each sprint to pay down technical debt.', m: 'technical debt',
    exJa: '技術的負債を返済するために、毎スプリント時間を確保する必要がある。', hl: '技術的負債' },
  { id: 'root-cause', t: 'root cause', k: 'phrase', c: 'it', lv: 1, ja: '根本原因',
    ex: 'The postmortem identified a misconfigured load balancer as the root cause.', m: 'root cause',
    exJa: '事後検証で、設定ミスのロードバランサーが根本原因だと特定された。', hl: '根本原因' },
  { id: 'roll-out', t: 'roll out', k: 'idiom', c: 'it', lv: 1, ja: '（段階的に）展開する、導入する',
    ex: "We'll roll out the feature to 10% of users first.", m: 'roll out',
    exJa: 'まずはユーザーの10%にその機能を展開する。', hl: '展開する' },
  { id: 'streamline', t: 'streamline', k: 'word', c: 'it', lv: 2, ja: '合理化する、効率化する',
    ex: 'The new CI pipeline streamlines our release process.', m: 'streamlines',
    exJa: '新しいCIパイプラインはリリース工程を効率化する。', hl: '効率化する' },
  { id: 'redundant', t: 'redundant', k: 'word', c: 'it', lv: 2, ja: '冗長な、余分な',
    ex: 'Remove the redundant checks to simplify the code.', m: 'redundant',
    exJa: 'コードを簡潔にするために冗長なチェックを削除して。', hl: '冗長な' },
  { id: 'intermittent', t: 'intermittent', k: 'word', c: 'it', lv: 3, ja: '断続的な、間欠的な',
    ex: 'Users are reporting intermittent timeouts on the login page.', m: 'intermittent',
    exJa: 'ログインページで断続的なタイムアウトが報告されている。', hl: '断続的な' },
  { id: 'edge-case', t: 'edge case', k: 'phrase', c: 'it', lv: 1, ja: '（境界付近の）まれなケース、エッジケース',
    ex: 'Make sure your tests cover edge cases such as empty input.', m: 'edge cases',
    exJa: '空の入力のようなまれなケースもテストでカバーするように。', hl: 'まれなケース' },
  { id: 'spin-up', t: 'spin up', k: 'idiom', c: 'it', lv: 2, ja: '（サーバー・環境を）立ち上げる',
    ex: 'Can you spin up a staging environment for the demo?', m: 'spin up',
    exJa: 'デモ用にステージング環境を立ち上げてもらえる？', hl: '立ち上げて' },
  { id: 'under-the-hood', t: 'under the hood', k: 'idiom', c: 'it', lv: 2, ja: '内部では、裏側で',
    ex: 'Under the hood, the service uses a message queue to process requests.', m: 'Under the hood',
    exJa: '内部では、そのサービスはメッセージキューでリクエストを処理している。', hl: '内部では' },
  { id: 'trade-off', t: 'trade-off', k: 'word', c: 'it', lv: 1, ja: '（相反する要素の）兼ね合い、トレードオフ',
    ex: "There's always a trade-off between consistency and availability.", m: 'trade-off',
    exJa: '一貫性と可用性の間には常に兼ね合いがある。', hl: '兼ね合い', alt: ['tradeoff', 'trade off'] },
  { id: 'robust', t: 'robust', k: 'word', c: 'it', lv: 1, ja: '堅牢な、頑健な',
    ex: 'We need a more robust error-handling strategy.', m: 'robust',
    exJa: 'より堅牢なエラー処理の方針が必要だ。', hl: '堅牢な' },
  { id: 'granular', t: 'granular', k: 'word', c: 'it', lv: 3, ja: 'きめ細かい、粒度の細かい',
    ex: 'The new dashboard gives us more granular control over permissions.', m: 'granular',
    exJa: '新しいダッシュボードで権限をよりきめ細かく管理できる。', hl: 'きめ細かく' },
  { id: 'bandwidth', t: 'bandwidth', k: 'word', c: 'it', lv: 2, ja: '（人の）余力、対応できる余裕',
    ex: "I don't have the bandwidth to take on another project this quarter.", m: 'bandwidth',
    exJa: '今四半期はもう一つプロジェクトを引き受ける余力がない。', hl: '余力' },

  // ---- ビジネス ----
  { id: 'touch-base', t: 'touch base', k: 'idiom', c: 'biz', lv: 1, ja: '（軽く）連絡を取る、打ち合わせる',
    ex: "Let's touch base next week to review the progress.", m: 'touch base',
    exJa: '来週、進捗確認のために連絡を取り合いましょう。', hl: '連絡を取り合いましょう' },
  { id: 'circle-back', t: 'circle back', k: 'idiom', c: 'biz', lv: 2, ja: '（後で）改めて話を戻す',
    ex: "Let me circle back on this once I've talked to the legal team.", m: 'circle back',
    exJa: '法務チームと話したら、この件について改めてご連絡します。', hl: '改めてご連絡します' },
  { id: 'stakeholder', t: 'stakeholder', k: 'word', c: 'biz', lv: 1, ja: '利害関係者、関係者',
    ex: 'We need approval from all key stakeholders before launch.', m: 'stakeholders',
    exJa: 'ローンチ前にすべての主要な利害関係者の承認が必要だ。', hl: '利害関係者' },
  { id: 'buy-in', t: 'buy-in', k: 'word', c: 'biz', lv: 2, ja: '（関係者の）賛同、支持',
    ex: 'Getting buy-in from senior management was harder than expected.', m: 'buy-in',
    exJa: '経営幹部の賛同を得るのは予想以上に難しかった。', hl: '賛同', alt: ['buy in'] },
  { id: 'same-page', t: 'on the same page', k: 'idiom', c: 'biz', lv: 1, ja: '認識が一致している',
    ex: "Before we start, let's make sure we're all on the same page.", m: 'on the same page',
    exJa: '始める前に、全員の認識が一致しているか確認しよう。', hl: '認識が一致している' },
  { id: 'ballpark', t: 'ballpark figure', k: 'phrase', c: 'biz', lv: 2, ja: 'おおよその数字、概算',
    ex: 'Can you give me a ballpark figure for the project cost?', m: 'ballpark figure',
    exJa: 'プロジェクト費用の概算を教えてもらえますか？', hl: '概算', alt: ['ballpark'] },
  { id: 'factor-in', t: 'factor in', k: 'idiom', c: 'biz', lv: 2, ja: '考慮に入れる、織り込む',
    ex: 'Did you factor in the cost of maintenance?', m: 'factor in',
    exJa: '保守費用は考慮に入れましたか？', hl: '考慮に入れましたか' },
  { id: 'contingency', t: 'contingency plan', k: 'phrase', c: 'biz', lv: 2, ja: '緊急時対応計画、代替策',
    ex: 'We should have a contingency plan in case the vendor misses the deadline.', m: 'contingency plan',
    exJa: 'ベンダーが納期に遅れた場合に備えて代替策を用意しておくべきだ。', hl: '代替策' },
  { id: 'allocate', t: 'allocate', k: 'word', c: 'biz', lv: 1, ja: '割り当てる、配分する',
    ex: "We've allocated two engineers to the migration project.", m: 'allocated',
    exJa: '移行プロジェクトにエンジニアを2名割り当てた。', hl: '割り当てた' },
  { id: 'feasible', t: 'feasible', k: 'word', c: 'biz', lv: 1, ja: '実現可能な',
    ex: 'Is it feasible to deliver this by the end of the month?', m: 'feasible',
    exJa: '月末までにこれを納品するのは実現可能ですか？', hl: '実現可能' },
  { id: 'pushback', t: 'pushback', k: 'word', c: 'biz', lv: 2, ja: '反発、抵抗',
    ex: 'We got some pushback from the sales team on the new pricing.', m: 'pushback',
    exJa: '新しい価格設定について営業チームから反発があった。', hl: '反発', alt: ['push back', 'push-back'] },
  { id: 'hit-the-ground', t: 'hit the ground running', k: 'idiom', c: 'biz', lv: 3, ja: '（着任直後から）すぐに全力で取りかかる',
    ex: 'She hit the ground running and closed two deals in her first week.', m: 'hit the ground running',
    exJa: '彼女は着任直後から全力で取りかかり、最初の週に2件の契約をまとめた。', hl: '着任直後から全力で取りかかり' },
  { id: 'scope-creep', t: 'scope creep', k: 'phrase', c: 'biz', lv: 2, ja: '（要件の）範囲の肥大化',
    ex: "We need to manage scope creep, or we'll never ship.", m: 'scope creep',
    exJa: '範囲の肥大化を管理しないと、いつまでもリリースできない。', hl: '範囲の肥大化' },
  { id: 'moving-forward', t: 'moving forward', k: 'phrase', c: 'biz', lv: 1, ja: '今後は',
    ex: 'Moving forward, all changes must be reviewed by two people.', m: 'Moving forward',
    exJa: '今後は、すべての変更を2人でレビューしなければならない。', hl: '今後は', alt: ['going forward'] },
  { id: 'earliest-convenience', t: 'at your earliest convenience', k: 'phrase', c: 'biz', lv: 2, ja: 'ご都合がつき次第',
    ex: 'Please review the attached document at your earliest convenience.', m: 'at your earliest convenience',
    exJa: 'ご都合がつき次第、添付資料をご確認ください。', hl: 'ご都合がつき次第' },
  { id: 'follow-up-on', t: 'follow up on', k: 'idiom', c: 'biz', lv: 1, ja: '～について追って確認する',
    ex: "I'm following up on the email I sent last week.", m: 'following up on',
    exJa: '先週お送りしたメールの件で確認のご連絡です。', hl: '確認のご連絡' },
  { id: 'align', t: 'align', k: 'word', c: 'biz', lv: 2, ja: '（方針・目標を）一致させる、すり合わせる',
    ex: "We need to align our roadmap with the company's strategic goals.", m: 'align',
    exJa: 'ロードマップを会社の戦略目標と一致させる必要がある。', hl: '一致させる' },
  { id: 'deliverable', t: 'deliverable', k: 'word', c: 'biz', lv: 1, ja: '成果物',
    ex: 'The main deliverable for this phase is a working prototype.', m: 'deliverable',
    exJa: 'このフェーズの主な成果物は動作するプロトタイプだ。', hl: '成果物' },
  { id: 'pragmatic', t: 'pragmatic', k: 'word', c: 'biz', lv: 2, ja: '現実的な、実際的な',
    ex: 'We took a pragmatic approach and fixed the most critical bugs first.', m: 'pragmatic',
    exJa: '現実的なアプローチをとり、最も重大なバグから修正した。', hl: '現実的な' },
  { id: 'elaborate', t: 'elaborate on', k: 'idiom', c: 'biz', lv: 2, ja: '～について詳しく説明する',
    ex: "Could you elaborate on what you mean by 'quick win'?", m: 'elaborate on',
    exJa: '「クイックウィン」とはどういう意味か、詳しく説明していただけますか？', hl: '詳しく説明して', alt: ['elaborate'] },

  // ---- 日常会話 ----
  { id: 'come-across-as', t: 'come across as', k: 'idiom', c: 'daily', lv: 2, ja: '～という印象を与える',
    ex: "He can come across as a bit arrogant, but he's actually very kind.", m: 'come across as',
    exJa: '彼は少し傲慢な印象を与えることがあるが、実はとても親切だ。', hl: '印象を与える' },
  { id: 'get-the-hang', t: 'get the hang of', k: 'idiom', c: 'daily', lv: 1, ja: '～のコツをつかむ',
    ex: 'It took me a while to get the hang of the new software.', m: 'get the hang of',
    exJa: '新しいソフトのコツをつかむまでしばらくかかった。', hl: 'コツをつかむ' },
  { id: 'reluctant', t: 'reluctant', k: 'word', c: 'daily', lv: 1, ja: '気が進まない、渋る',
    ex: 'She was reluctant to share her opinion in front of everyone.', m: 'reluctant',
    exJa: '彼女はみんなの前で意見を言うのに気が進まなかった。', hl: '気が進まなかった' },
  { id: 'inevitably', t: 'inevitably', k: 'word', c: 'daily', lv: 2, ja: '必然的に、どうしても',
    ex: 'Inevitably, some mistakes will happen when you try something new.', m: 'Inevitably',
    exJa: '新しいことに挑戦すれば、どうしてもミスは起こるものだ。', hl: 'どうしても' },
  { id: 'put-up-with', t: 'put up with', k: 'idiom', c: 'daily', lv: 1, ja: '～を我慢する',
    ex: "I can't put up with the noise from upstairs anymore.", m: 'put up with',
    exJa: '上の階の騒音にはもう我慢できない。', hl: '我慢できない' },
  { id: 'blessing-in-disguise', t: 'a blessing in disguise', k: 'idiom', c: 'daily', lv: 2, ja: '一見不運だが実は幸運なこと',
    ex: 'Losing that job turned out to be a blessing in disguise.', m: 'a blessing in disguise',
    exJa: 'あの仕事を失ったことは、結果的に災い転じて福となった。', hl: '災い転じて福となった', alt: ['blessing in disguise'] },
  { id: 'overwhelmed', t: 'overwhelmed', k: 'word', c: 'daily', lv: 1, ja: '圧倒されて、手に負えなくて',
    ex: 'I felt completely overwhelmed by the amount of work.', m: 'overwhelmed',
    exJa: '仕事の量に完全に圧倒されてしまった。', hl: '圧倒されて' },
  { id: 'ambiguous', t: 'ambiguous', k: 'word', c: 'daily', lv: 1, ja: '曖昧な、複数の解釈ができる',
    ex: 'The instructions were ambiguous, so everyone interpreted them differently.', m: 'ambiguous',
    exJa: '指示が曖昧だったので、皆が違う解釈をした。', hl: '曖昧だった' },
  { id: 'cup-of-tea', t: 'not my cup of tea', k: 'idiom', c: 'daily', lv: 2, ja: '自分の好みではない',
    ex: "Horror movies aren't really my cup of tea.", m: 'my cup of tea',
    exJa: 'ホラー映画はあまり好みじゃない。', hl: '好みじゃない', alt: ['my cup of tea', 'cup of tea'] },
  { id: 'make-ends-meet', t: 'make ends meet', k: 'idiom', c: 'daily', lv: 2, ja: '収入内でやりくりする',
    ex: 'Many people work two jobs just to make ends meet.', m: 'make ends meet',
    exJa: '多くの人がやりくりするためだけに仕事を掛け持ちしている。', hl: 'やりくりする' },
  { id: 'by-and-large', t: 'by and large', k: 'idiom', c: 'daily', lv: 3, ja: '概して、全体的に見て',
    ex: 'By and large, the trip went smoothly.', m: 'By and large',
    exJa: '概して、旅行は順調だった。', hl: '概して' },
  { id: 'take-for-granted', t: 'take sth for granted', k: 'idiom', c: 'daily', lv: 2, ja: '～を当たり前だと思う',
    ex: 'We often take our health for granted until we get sick.', m: 'take our health for granted',
    exJa: '私たちは病気になるまで健康を当たり前だと思いがちだ。', hl: '当たり前だと思い', alt: ['take for granted', 'take something for granted', 'take it for granted'] },
  { id: 'procrastinate', t: 'procrastinate', k: 'word', c: 'daily', lv: 2, ja: '（やるべきことを）先延ばしにする',
    ex: 'I tend to procrastinate when a task feels overwhelming.', m: 'procrastinate',
    exJa: '大変そうな作業だと先延ばしにしがちだ。', hl: '先延ばしにし' },
  { id: 'on-the-fence', t: 'on the fence', k: 'idiom', c: 'daily', lv: 2, ja: '決めかねている、どっちつかずで',
    ex: "I'm still on the fence about moving to a new city.", m: 'on the fence',
    exJa: '新しい街に引っ越すかどうか、まだ決めかねている。', hl: '決めかねている' },
  { id: 'jump-to-conclusions', t: 'jump to conclusions', k: 'phrase', c: 'daily', lv: 1, ja: '早合点する、結論を急ぐ',
    ex: "Let's not jump to conclusions before we know all the facts.", m: 'jump to conclusions',
    exJa: '事実が全部わかるまで早合点するのはやめよう。', hl: '早合点する' },
  { id: 'nuance', t: 'nuance', k: 'word', c: 'daily', lv: 2, ja: '微妙な差異、ニュアンス',
    ex: "It's hard to capture the nuances of the joke in translation.", m: 'nuances',
    exJa: '翻訳でそのジョークの微妙なニュアンスを伝えるのは難しい。', hl: '微妙なニュアンス' },
  { id: 'hit-it-off', t: 'hit it off', k: 'idiom', c: 'daily', lv: 2, ja: '（初対面で）意気投合する',
    ex: 'We hit it off right away and talked for hours.', m: 'hit it off',
    exJa: '私たちはすぐに意気投合して何時間も話した。', hl: '意気投合して' },
];
