// C2 レベル以上の初期単語セット。
// t: 見出し語 / k: 種類 (word|idiom|phrase) / c: カテゴリ (daily|biz|it) / lv: 難易度 1-3（C2内での相対難度）
// ja: 意味 / ex: 例文 / m: 例文中で強調する部分 / exJa: 例文和訳 / hl: 和訳中の該当部分
// alt: 和訳→英語で正解として認める別表記
export const CATEGORIES = { daily: '日常会話', biz: 'ビジネス', it: 'IT' };
export const KINDS = { word: '単語', idiom: '熟語', phrase: 'フレーズ' };

export const WORDS = [
  // ---- IT ----
  { id: 'c2-idempotent', t: 'idempotent', k: 'word', c: 'it', lv: 2, ja: '冪等な（何度実行しても結果が同じ）',
    ex: "Make the endpoint idempotent so that retries don't create duplicate orders.", m: 'idempotent',
    exJa: 'リトライで注文が重複しないよう、エンドポイントを冪等にして。', hl: '冪等に' },
  { id: 'c2-obviate', t: 'obviate', k: 'word', c: 'it', lv: 3, ja: '（必要・困難を）不要にする、未然に取り除く',
    ex: 'Caching at the edge obviates the need for a separate CDN.', m: 'obviates',
    exJa: 'エッジでキャッシュすれば、別途CDNを用意する必要がなくなる。', hl: '必要がなくなる' },
  { id: 'c2-brittle', t: 'brittle', k: 'word', c: 'it', lv: 1, ja: '脆い、（変更に）壊れやすい',
    ex: 'These end-to-end tests are brittle and break whenever the UI changes.', m: 'brittle',
    exJa: 'このE2Eテストは脆く、UIが変わるたびに壊れる。', hl: '脆く' },
  { id: 'c2-bespoke', t: 'bespoke', k: 'word', c: 'it', lv: 2, ja: '特注の、独自開発の',
    ex: 'Rather than building a bespoke solution, we opted for an off-the-shelf product.', m: 'bespoke',
    exJa: '独自開発のソリューションを作るのではなく、既製品を選んだ。', hl: '独自開発の' },
  { id: 'c2-cobble-together', t: 'cobble together', k: 'idiom', c: 'it', lv: 2, ja: '（ありあわせで）急ごしらえする',
    ex: 'We cobbled together a prototype over the weekend.', m: 'cobbled together',
    exJa: '週末にプロトタイプを急ごしらえした。', hl: '急ごしらえした' },
  { id: 'c2-ossified', t: 'ossified', k: 'word', c: 'it', lv: 3, ja: '硬直化した、柔軟性を失った',
    ex: 'The codebase has become ossified; nobody dares to touch the core modules.', m: 'ossified',
    exJa: 'コードベースは硬直化し、誰もコアモジュールに手を出そうとしない。', hl: '硬直化し' },
  { id: 'c2-kludge', t: 'kludge', k: 'word', c: 'it', lv: 2, ja: 'その場しのぎの（不格好な）解決策',
    ex: "This fix is a kludge, but it'll keep the service up until Monday.", m: 'kludge',
    exJa: 'この修正はその場しのぎだが、月曜まではサービスを維持できる。', hl: 'その場しのぎ', alt: ['kluge'] },
  { id: 'c2-graceful-degradation', t: 'graceful degradation', k: 'phrase', c: 'it', lv: 2, ja: '（障害時の）段階的な機能縮退',
    ex: 'Graceful degradation keeps the app usable even when the recommendation service is down.', m: 'Graceful degradation',
    exJa: '機能の段階的縮退により、レコメンドサービスが停止してもアプリは使える状態を保つ。', hl: '機能の段階的縮退' },
  { id: 'c2-heuristic', t: 'heuristic', k: 'word', c: 'it', lv: 1, ja: '経験則、発見的手法',
    ex: 'We use a simple heuristic to flag suspicious logins.', m: 'heuristic',
    exJa: '不審なログインを検出するのに単純な経験則を使っている。', hl: '経験則' },
  { id: 'c2-orthogonal', t: 'orthogonal', k: 'word', c: 'it', lv: 2, ja: '（互いに）無関係な、独立した',
    ex: "That issue is orthogonal to the performance problem we're discussing.", m: 'orthogonal',
    exJa: 'その問題は、今議論しているパフォーマンスの問題とは無関係だ。', hl: '無関係だ' },
  { id: 'c2-canonical', t: 'canonical', k: 'word', c: 'it', lv: 1, ja: '正式な、標準とされる',
    ex: 'This repository is the canonical source for our API schemas.', m: 'canonical',
    exJa: 'このリポジトリがAPIスキーマの正式な情報源だ。', hl: '正式な' },
  { id: 'c2-bikeshedding', t: 'bikeshedding', k: 'word', c: 'it', lv: 3, ja: '些末なことに時間を費やす議論',
    ex: "Let's stop bikeshedding over variable names and focus on the architecture.", m: 'bikeshedding',
    exJa: '変数名についての些末な議論はやめて、アーキテクチャに集中しよう。', hl: '些末な議論', alt: ['bike shedding', 'bikeshed'] },
  { id: 'c2-yak-shaving', t: 'yak shaving', k: 'phrase', c: 'it', lv: 3, ja: '本題に至るまでの延々と続く枝葉の作業',
    ex: 'What started as a simple build fix turned into an afternoon of yak shaving.', m: 'yak shaving',
    exJa: '単純なビルド修正のつもりが、午後じゅう枝葉の作業に追われる羽目になった。', hl: '枝葉の作業', alt: ['yak-shaving'] },
  { id: 'c2-stopgap', t: 'stopgap', k: 'word', c: 'it', lv: 1, ja: '一時しのぎ（の）、間に合わせ（の）',
    ex: 'This is only a stopgap measure until the new system goes live.', m: 'stopgap',
    exJa: 'これは新システムが稼働するまでの一時しのぎの措置にすぎない。', hl: '一時しのぎの' },
  { id: 'c2-latent', t: 'latent', k: 'word', c: 'it', lv: 1, ja: '潜在的な、表に出ていない',
    ex: 'The refactor exposed a latent bug in the payment module.', m: 'latent',
    exJa: 'リファクタリングで決済モジュールの潜在的なバグが表面化した。', hl: '潜在的な' },
  { id: 'c2-proliferation', t: 'proliferation', k: 'word', c: 'it', lv: 2, ja: '急増、乱立',
    ex: 'The proliferation of microservices has made debugging much harder.', m: 'proliferation',
    exJa: 'マイクロサービスの乱立で、デバッグがはるかに難しくなった。', hl: '乱立' },
  { id: 'c2-arcane', t: 'arcane', k: 'word', c: 'it', lv: 2, ja: '難解な、一部の人にしかわからない',
    ex: 'The deployment relies on arcane scripts that only one engineer understands.', m: 'arcane',
    exJa: 'デプロイは、一人のエンジニアしか理解していない難解なスクリプトに依存している。', hl: '難解な' },
  { id: 'c2-dogfood', t: 'dogfood', k: 'word', c: 'it', lv: 2, ja: '（自社製品を）社内で実際に使って試す',
    ex: 'We dogfood every release internally before shipping it to customers.', m: 'dogfood',
    exJa: '顧客に出す前に、すべてのリリースを社内で自ら使って試している。', hl: '社内で自ら使って試している', alt: ['dogfooding', 'eat our own dog food'] },
  { id: 'c2-conflate', t: 'conflate', k: 'word', c: 'it', lv: 2, ja: '（別のものを）混同する、一緒くたにする',
    ex: "Don't conflate authentication with authorization.", m: 'conflate',
    exJa: '認証と認可を混同しないで。', hl: '混同しないで' },

  // ---- ビジネス ----
  { id: 'c2-move-the-needle', t: 'move the needle', k: 'idiom', c: 'biz', lv: 2, ja: '目に見える変化・成果をもたらす',
    ex: "These tweaks are nice, but they won't move the needle on revenue.", m: 'move the needle',
    exJa: 'この微調整も悪くないが、売上に目に見える影響は与えないだろう。', hl: '目に見える影響は与えない' },
  { id: 'c2-table', t: 'table', k: 'word', c: 'biz', lv: 3, ja: '（米）（議題を）棚上げにする ※英では「提出する」',
    ex: "Let's table this discussion until we have more data.", m: 'table',
    exJa: 'データが揃うまで、この議論は棚上げにしよう。', hl: '棚上げにしよう' },
  { id: 'c2-due-diligence', t: 'due diligence', k: 'phrase', c: 'biz', lv: 1, ja: '（契約・投資前の）十分な調査、適正評価',
    ex: 'We need to do our due diligence before signing with a new vendor.', m: 'due diligence',
    exJa: '新しいベンダーと契約する前に、十分な調査を行う必要がある。', hl: '十分な調査' },
  { id: 'c2-leeway', t: 'leeway', k: 'word', c: 'biz', lv: 1, ja: '（時間・行動の）余裕、裁量の余地',
    ex: 'The manager gave us some leeway on the deadline.', m: 'leeway',
    exJa: 'マネージャーは締め切りに多少の猶予をくれた。', hl: '猶予' },
  { id: 'c2-hedge-bets', t: "hedge one's bets", k: 'idiom', c: 'biz', lv: 2, ja: '両天秤をかける、リスクを分散する',
    ex: "We're hedging our bets by working with two suppliers.", m: 'hedging our bets',
    exJa: '2社のサプライヤーと取引して、両天秤をかけている。', hl: '両天秤をかけている', alt: ['hedge your bets', 'hedge our bets'] },
  { id: 'c2-tacit', t: 'tacit', k: 'word', c: 'biz', lv: 1, ja: '暗黙の',
    ex: 'There was a tacit agreement not to discuss salaries.', m: 'tacit',
    exJa: '給与の話はしないという暗黙の了解があった。', hl: '暗黙の' },
  { id: 'c2-acquiesce', t: 'acquiesce', k: 'word', c: 'biz', lv: 3, ja: '（不本意ながら）黙って従う、渋々同意する',
    ex: "The board eventually acquiesced to the CEO's proposal.", m: 'acquiesced',
    exJa: '取締役会は最終的にCEOの提案を渋々受け入れた。', hl: '渋々受け入れた' },
  { id: 'c2-loggerheads', t: 'at loggerheads', k: 'idiom', c: 'biz', lv: 3, ja: '（激しく）対立して、反目して',
    ex: 'Engineering and sales have been at loggerheads over the release date.', m: 'at loggerheads',
    exJa: '開発と営業はリリース日を巡って対立している。', hl: '対立している' },
  { id: 'c2-read-the-room', t: 'read the room', k: 'idiom', c: 'biz', lv: 1, ja: '場の空気を読む',
    ex: 'He failed to read the room and pitched the idea at the worst possible time.', m: 'read the room',
    exJa: '彼は空気を読めず、最悪のタイミングでその案を売り込んだ。', hl: '空気を読めず' },
  { id: 'c2-tall-order', t: 'a tall order', k: 'idiom', c: 'biz', lv: 2, ja: '無理な注文、難しい要求',
    ex: 'Delivering all these features by Friday is a tall order.', m: 'a tall order',
    exJa: '金曜までにこれらの機能をすべて納品するのは無理な注文だ。', hl: '無理な注文', alt: ['tall order'] },
  { id: 'c2-incumbent', t: 'incumbent', k: 'word', c: 'biz', lv: 2, ja: '既存の（大手）企業、現職者',
    ex: 'Startups are challenging the incumbents in the payments industry.', m: 'incumbents',
    exJa: 'スタートアップが決済業界の既存大手に挑んでいる。', hl: '既存大手' },
  { id: 'c2-ramifications', t: 'ramifications', k: 'word', c: 'biz', lv: 2, ja: '（予期しない）影響、波及的な結果',
    ex: 'Have you considered the legal ramifications of this decision?', m: 'ramifications',
    exJa: 'この決定の法的な影響は検討しましたか？', hl: '影響', alt: ['ramification'] },
  { id: 'c2-salient', t: 'salient', k: 'word', c: 'biz', lv: 2, ja: '顕著な、最も重要な',
    ex: 'Let me summarize the salient points of the proposal.', m: 'salient points',
    exJa: '提案の要点をまとめさせてください。', hl: '要点' },
  { id: 'c2-untenable', t: 'untenable', k: 'word', c: 'biz', lv: 2, ja: '維持できない、擁護できない',
    ex: 'The current pricing model is untenable in the long run.', m: 'untenable',
    exJa: '現在の価格モデルは長期的には維持できない。', hl: '維持できない' },
  { id: 'c2-circumvent', t: 'circumvent', k: 'word', c: 'biz', lv: 1, ja: '（規則などを）回避する、すり抜ける',
    ex: 'Some teams circumvented the approval process to ship faster.', m: 'circumvented',
    exJa: '早くリリースするために、承認プロセスをすり抜けたチームもあった。', hl: 'すり抜けた' },
  { id: 'c2-cede', t: 'cede', k: 'word', c: 'biz', lv: 2, ja: '（権利・領域を）譲り渡す、明け渡す',
    ex: 'The company was forced to cede market share to its rivals.', m: 'cede',
    exJa: 'その会社は競合に市場シェアを明け渡さざるを得なかった。', hl: '明け渡さざるを得なかった' },
  { id: 'c2-preempt', t: 'preempt', k: 'word', c: 'biz', lv: 2, ja: '先手を打って防ぐ、機先を制する',
    ex: 'We issued a statement to preempt any speculation.', m: 'preempt',
    exJa: '憶測を先回りして防ぐため、声明を出した。', hl: '先回りして防ぐ', alt: ['pre-empt'] },
  { id: 'c2-galvanize', t: 'galvanize', k: 'word', c: 'biz', lv: 2, ja: '奮い立たせる、（行動へ）駆り立てる',
    ex: "The CEO's speech galvanized the team into action.", m: 'galvanized',
    exJa: 'CEOのスピーチがチームを奮い立たせ、行動へと駆り立てた。', hl: '奮い立たせ', alt: ['galvanise'] },
  { id: 'c2-under-the-bus', t: 'throw sb under the bus', k: 'idiom', c: 'biz', lv: 2, ja: '（保身のため）人を犠牲にする、責任をなすりつける',
    ex: 'He threw his own team under the bus to save face.', m: 'threw his own team under the bus',
    exJa: '彼は面目を保つために、自分のチームに責任をなすりつけた。', hl: '責任をなすりつけた' },
  { id: 'c2-boilerplate', t: 'boilerplate', k: 'word', c: 'biz', lv: 1, ja: '定型文、決まり文句',
    ex: 'Most of the contract is boilerplate, but check the liability clause.', m: 'boilerplate',
    exJa: '契約書の大部分は定型文だが、責任条項は確認して。', hl: '定型文' },

  // ---- 日常会話 ----
  { id: 'c2-ubiquitous', t: 'ubiquitous', k: 'word', c: 'daily', lv: 1, ja: 'どこにでもある、遍在する',
    ex: 'Smartphones have become ubiquitous, even among the elderly.', m: 'ubiquitous',
    exJa: 'スマートフォンは高齢者の間でもどこにでもあるものになった。', hl: 'どこにでもある' },
  { id: 'c2-perfunctory', t: 'perfunctory', k: 'word', c: 'daily', lv: 3, ja: 'おざなりな、形だけの',
    ex: 'He gave me a perfunctory nod and kept typing.', m: 'perfunctory',
    exJa: '彼はおざなりにうなずいただけで、タイピングを続けた。', hl: 'おざなりに' },
  { id: 'c2-serendipity', t: 'serendipity', k: 'word', c: 'daily', lv: 1, ja: '思いがけない幸運な発見・出会い',
    ex: 'Meeting my business partner at a wedding was pure serendipity.', m: 'serendipity',
    exJa: '結婚式でビジネスパートナーに出会ったのは、まったくの偶然の幸運だった。', hl: '偶然の幸運' },
  { id: 'c2-disingenuous', t: 'disingenuous', k: 'word', c: 'daily', lv: 2, ja: '不誠実な、（知っているのに）しらばくれた',
    ex: "It's disingenuous to claim you didn't know about the problem.", m: 'disingenuous',
    exJa: 'その問題を知らなかったと言うのは不誠実だ。', hl: '不誠実だ' },
  { id: 'c2-quintessential', t: 'quintessential', k: 'word', c: 'daily', lv: 2, ja: '典型的な、真髄の',
    ex: 'It was the quintessential British afternoon: rain, tea, and polite complaints.', m: 'quintessential',
    exJa: '雨、紅茶、そして丁寧な愚痴という、典型的なイギリスの午後だった。', hl: '典型的な' },
  { id: 'c2-ambivalent', t: 'ambivalent', k: 'word', c: 'daily', lv: 1, ja: '相反する感情を抱いた、複雑な気持ちの',
    ex: 'I feel ambivalent about moving abroad.', m: 'ambivalent',
    exJa: '海外に引っ越すことについては、複雑な気持ちだ。', hl: '複雑な気持ち' },
  { id: 'c2-sanguine', t: 'sanguine', k: 'word', c: 'daily', lv: 3, ja: '（困難な状況でも）楽観的な',
    ex: 'She remained sanguine despite the setbacks.', m: 'sanguine',
    exJa: '彼女は挫折があっても楽観的なままだった。', hl: '楽観的な' },
  { id: 'c2-capricious', t: 'capricious', k: 'word', c: 'daily', lv: 2, ja: '気まぐれな、予測できない',
    ex: 'The weather in the mountains is notoriously capricious.', m: 'capricious',
    exJa: '山の天気は気まぐれなことで有名だ。', hl: '気まぐれな' },
  { id: 'c2-damp-squib', t: 'a damp squib', k: 'idiom', c: 'daily', lv: 3, ja: '（英）期待外れ、不発に終わったもの',
    ex: 'The much-hyped party turned out to be a damp squib.', m: 'a damp squib',
    exJa: '大いに宣伝されたパーティーは期待外れに終わった。', hl: '期待外れに終わった', alt: ['damp squib'] },
  { id: 'c2-tangent', t: 'go off on a tangent', k: 'idiom', c: 'daily', lv: 2, ja: '（話が）脱線する',
    ex: 'Sorry, I went off on a tangent. Where was I?', m: 'went off on a tangent',
    exJa: 'ごめん、話が脱線しちゃった。どこまで話したっけ？', hl: '話が脱線しちゃった' },
  { id: 'c2-pinch-of-salt', t: 'take sth with a pinch of salt', k: 'idiom', c: 'daily', lv: 2, ja: '（話を）割り引いて聞く、鵜呑みにしない',
    ex: 'Take his advice with a pinch of salt; he tends to exaggerate.', m: 'Take his advice with a pinch of salt',
    exJa: '彼のアドバイスは割り引いて聞いたほうがいい。大げさに言いがちだから。', hl: '割り引いて聞いた',
    alt: ['take it with a pinch of salt', 'take with a grain of salt', 'take it with a grain of salt', 'with a pinch of salt'] },
  { id: 'c2-inveterate', t: 'inveterate', k: 'word', c: 'daily', lv: 3, ja: '根っからの、常習的な',
    ex: "He's an inveterate liar, so don't believe a word he says.", m: 'inveterate',
    exJa: '彼は根っからの嘘つきだから、一言も信じちゃだめだ。', hl: '根っからの' },
  { id: 'c2-vicarious', t: 'vicarious', k: 'word', c: 'daily', lv: 2, ja: '（他人の体験を通じて）間接的に味わう',
    ex: 'I get a vicarious thrill from watching travel vlogs.', m: 'vicarious',
    exJa: '旅行Vlogを見て、人の体験を通じてわくわく感を味わっている。', hl: '人の体験を通じて' },
  { id: 'c2-tenterhooks', t: 'on tenterhooks', k: 'idiom', c: 'daily', lv: 3, ja: '気をもんで、やきもきして',
    ex: 'We were on tenterhooks waiting for the test results.', m: 'on tenterhooks',
    exJa: '検査結果を待つ間、私たちはやきもきしていた。', hl: 'やきもきしていた' },
  { id: 'c2-ostensibly', t: 'ostensibly', k: 'word', c: 'daily', lv: 2, ja: '表向きは、建前上は',
    ex: 'He came by, ostensibly to return a book, but really to chat.', m: 'ostensibly',
    exJa: '彼は表向きは本を返しに来たが、実はおしゃべりしたかったのだ。', hl: '表向きは' },
  { id: 'c2-desultory', t: 'desultory', k: 'word', c: 'daily', lv: 3, ja: 'とりとめのない、散漫な',
    ex: 'We had a desultory conversation about the weather.', m: 'desultory',
    exJa: '天気についてとりとめのない会話をした。', hl: 'とりとめのない' },
  { id: 'c2-idiosyncratic', t: 'idiosyncratic', k: 'word', c: 'daily', lv: 1, ja: '独特の、風変わりな',
    ex: 'She has an idiosyncratic way of organizing her bookshelves.', m: 'idiosyncratic',
    exJa: '彼女は本棚の整理の仕方が独特だ。', hl: '独特だ' },
  { id: 'c2-comeuppance', t: "get one's comeuppance", k: 'idiom', c: 'daily', lv: 3, ja: '当然の報いを受ける',
    ex: 'The bully finally got his comeuppance.', m: 'got his comeuppance',
    exJa: 'いじめっ子はついに当然の報いを受けた。', hl: '当然の報いを受けた', alt: ['get his comeuppance', 'get your comeuppance'] },
  { id: 'c2-wayside', t: 'fall by the wayside', k: 'idiom', c: 'daily', lv: 2, ja: '（途中で）立ち消えになる、脱落する',
    ex: "My New Year's resolutions usually fall by the wayside by February.", m: 'fall by the wayside',
    exJa: '新年の抱負はたいてい2月までに立ち消えになる。', hl: '立ち消えになる' },
];
