// No.201–300
export default [
  ['bits and pieces', 'n', 'small items or parts of various kinds', 'こまごましたもの', 'I need to pick up a few bits and pieces from the store.', '店でこまごました物をいくつか買わないと。'],
  ['silver lining', 'n', 'a positive aspect of a bad situation', '不幸中の幸い、明るい兆し', 'The silver lining is that we learned a lot.', '不幸中の幸いは、多くを学べたことだ。'],
  ['take sth to heart', 'v', 'take sth seriously and be affected by it', '～を真剣に受け止める、気に病む', "Don't take his criticism to heart.", '彼の批判を気にしすぎないで。'],
  ['park sth', 'v', 'put off discussing sth until later', '（議題を）一旦保留にする', "Let's park that idea and come back to it later.", 'その案は一旦保留にして、後で戻ろう。', 'postpone'],
  ['by hook or by crook', 'a', 'by any means possible', 'どんな手を使っても', "We'll finish this by hook or by crook.", 'どんな手を使ってもこれを終わらせる。'],
  ['sense-check', 'v', 'review sth to make sure it is reasonable', '（妥当か）ざっと確認する', 'Can you sense-check my numbers?', '私の数字が妥当かざっと見てもらえる？', 'check'],
  ['stumped', 'a', 'completely puzzled and unable to answer', 'お手上げの、途方に暮れた', 'This question has me stumped.', 'この質問にはお手上げだ。'],
  ['circle back to sth/sb', 'v', 'return to a topic or person later', '（後で）～に立ち戻る、改めて連絡する', "Let's circle back to this after lunch.", '昼食後にこの件に戻りましょう。'],
  ['hard taskmaster', 'n', 'person who demands a lot of work from others', '厳しく仕事を課す人', 'Our professor is a hard taskmaster.', '私たちの教授は課題に厳しい人だ。'],
  ['night and day', 'a', 'completely different', 'まったく違う、雲泥の差', 'The difference in quality is night and day.', '品質の差は雲泥の差だ。'],
  ["burst sb's bubble", 'v', "suddenly ruin sb's happy belief or illusion", '（人の）夢・幻想を壊す', 'I hate to burst your bubble, but the trip is cancelled.', '夢を壊して悪いけど、旅行は中止だ。'],
  ["drag sb's name through the mud", 'v', "publicly damage sb's reputation", '（人の）評判を落とす、名誉を傷つける', 'The tabloids dragged his name through the mud.', 'タブロイド紙が彼の評判を地に落とした。'],
  ['deep-dive', 'n', 'thorough, detailed analysis', '詳細な分析、掘り下げ', "Let's do a deep-dive into the churn data.", '解約データを詳しく掘り下げよう。'],
  ['boil down to sth', 'v', 'have sth as the essential point', '要するに～ということになる', 'It all boils down to money.', '結局はお金の問題だ。'],
  ['hit the ground running', 'v', 'start sth new energetically and succeed quickly', '着任早々すぐに成果を出す', 'She hit the ground running at her new job.', '彼女は新しい職場で初日から全力で取りかかった。'],
  ['wake up on the wrong side of the bed', 'v', 'be in a bad mood all day for no clear reason', '朝から機嫌が悪い', 'Did you wake up on the wrong side of the bed?', '朝から機嫌悪いね？'],
  ['low-hanging fruit', 'n', 'an easy goal that gives quick results', '簡単に達成できる目標、手っ取り早い成果', "Let's start with the low-hanging fruit.", 'まず手っ取り早く成果が出るものから始めよう。'],
  ['icebreaker', 'n', 'activity that helps strangers relax with each other', '緊張をほぐすための活動、アイスブレイク', 'We played a quick game as an icebreaker.', 'アイスブレイクとして簡単なゲームをした。'],
  ['mock sth up', 'v', 'make a rough draft or model of sth', '～の試作・モックを作る', "I'll mock up the new homepage.", '新しいトップページのモックを作るよ。'],
  ['or so', 'x', 'approximately', '～かそこら、～くらい', "It'll take an hour or so.", '1時間かそこらかかるだろう。', 'approx'],
  ['jack-of-all-trades', 'n', 'person who can do many different kinds of work', '何でも屋、多才な人', "In a startup, you have to be a jack-of-all-trades.", 'スタートアップでは何でもこなせなければならない。'],
  ['vanilla', 'a', 'plain and ordinary', 'ありきたりの、標準的な', "It's a pretty vanilla setup, nothing custom.", 'かなり標準的な構成で、カスタムは何もない。', 'boring'],
  ['hard-headed', 'a', 'stubborn; (also) practical and unsentimental', '頑固な；現実的な', "He's too hard-headed to admit he's wrong.", '彼は頑固すぎて自分の間違いを認めない。'],
  ["play devil's advocate", 'v', 'argue the opposite side to test an idea', 'あえて反対意見を述べる', "Let me play devil's advocate for a second.", 'ちょっとあえて反対の立場から言わせて。'],
  ['crystalize sth', 'v', 'make an idea clear and definite', '（考えを）具体化する、固める', 'The meeting helped crystalize our strategy.', 'その会議で戦略が固まった。', 'finish'],
  ['D and M', 'n', '(informal) a deep and meaningful conversation', '深くて真剣な会話', 'We had a real D and M last night.', '昨夜は本音で深い話をした。'],
  ['people person', 'n', 'someone who enjoys being with other people', '人付き合いが好きな人', "She's a natural people person.", '彼女は根っからの人好きだ。'],
  ['get sth over the line', 'v', 'complete sth successfully', '～をやり遂げる、成立させる', 'We worked all weekend to get the deal over the line.', '取引を成立させるために週末も働いた。', 'finish'],
  ['branch out', 'v', 'expand into new areas', '手を広げる、新分野に進出する', 'The company is branching out into healthcare.', 'その会社は医療分野に手を広げている。'],
  ['out of pocket', 'a', "paid with one's own money", '自腹で', 'I paid for the taxi out of pocket.', 'タクシー代は自腹で払った。'],
  ['wordsmith sth', 'v', 'polish the wording of sth', '（文章を）推敲する', 'Can you wordsmith this paragraph?', 'この段落の言い回しを整えてもらえる？'],
  ['watered-down', 'a', 'made weaker or less effective', '骨抜きにされた、薄められた', 'They passed a watered-down version of the bill.', '骨抜きにされた法案が可決された。'],
  ['fish for compliments', 'v', 'try to get praise in an indirect way', 'お世辞を引き出そうとする', 'Is she fishing for compliments again?', '彼女、またほめてほしがってる？'],
  ['meet sb halfway', 'v', 'reach a compromise with sb', '（人と）歩み寄る', "If you lower the price, we'll meet you halfway.", '価格を下げてくれるなら、こちらも歩み寄ります。'],
  ['weed out sth/sb', 'v', 'identify and remove unwanted things or people', '～を取り除く、ふるい落とす', 'The test is designed to weed out weak candidates.', 'その試験は力不足の候補者をふるい落とすためのものだ。'],
  ['better half', 'n', "one's husband, wife or partner", '配偶者、パートナー', "I'll have to check with my better half.", '相方に確認しないと。'],
  ['hit pause', 'v', 'stop sth temporarily', '一時中断する', "Let's hit pause on hiring until next year.", '採用は来年まで一時中断しよう。'],
  ['wind down', 'v', 'relax after activity; (also) gradually come to an end', 'くつろぐ；徐々に終わる', 'I read a book to wind down before bed.', '寝る前は本を読んでリラックスする。', 'relax'],
  ['make a killing', 'v', 'make a lot of money quickly', '大もうけする', 'He made a killing on the stock market.', '彼は株で大もうけした。'],
  ['take a stab in the dark', 'v', 'make a complete guess', '当てずっぽうで言う', "I'll take a stab in the dark — is it 42?", '当てずっぽうだけど、42？', 'guess'],
  ['take sth with a grain of salt', 'v', 'not completely believe sth', '～を割り引いて聞く', 'Take online reviews with a grain of salt.', 'ネットのレビューは割り引いて見たほうがいい。'],
  ['unwritten rule', 'n', 'rule everyone follows although it is not written down', '暗黙のルール', "It's an unwritten rule not to eat at your desk.", '自席で食べないのが暗黙のルールだ。'],
  ['treading water', 'a', 'making no progress', '足踏み状態で、現状維持で', 'My career has been treading water for years.', '私のキャリアは何年も足踏み状態だ。', 'stuck'],
  ['grunt work', 'n', 'boring, routine work', '単調な下働き、雑用', 'Interns usually get stuck with the grunt work.', 'インターンはたいてい雑用を押し付けられる。'],
  ["hold one's cards close to one's chest", 'v', "keep one's plans secret", '手の内を明かさない', 'The CEO is holding her cards close to her chest.', 'CEOは手の内を明かさずにいる。', 'secret'],
  ['unheard of', 'a', 'never having happened before', '前代未聞の、前例のない', 'Working from home was almost unheard of 20 years ago.', '20年前、在宅勤務はほとんど前例がなかった。'],
  ["put sb's name in the hat", 'v', 'nominate sb as a candidate', '（人を）候補に推す', "I put your name in the hat for the team lead role.", 'チームリーダー候補に君の名前を挙げておいたよ。'],
  ["out of sb's league", 'a', 'too good or too expensive for sb', '（人には）高嶺の花、手の届かない', 'That house is way out of our league.', 'あの家は私たちにはとても手が届かない。'],
  ['think back to sth', 'v', 'remember sth from the past', '～を思い返す', 'Think back to your first day at work.', '初出勤の日を思い返してみて。'],
  ['leave sb high and dry', 'v', 'leave sb without help or support', '（人を）見捨てる、置き去りにする', 'The contractor left us high and dry.', '業者に見捨てられてしまった。'],

  ['lucky break', 'n', 'fortunate opportunity', '幸運なチャンス', 'Getting that interview was a lucky break.', 'その面接を受けられたのは幸運だった。'],
  ["put one's best foot forward", 'v', 'try to make the best possible impression', '最善を尽くす、良いところを見せる', 'Put your best foot forward in the interview.', '面接ではベストを尽くして。', 'effort'],
  ['have the final say', 'v', 'have the authority to make the final decision', '最終決定権を持つ', 'The client has the final say on the design.', 'デザインの最終決定権はクライアントにある。', 'decide'],
  ['blow it', 'v', 'waste an opportunity by making a mistake', 'しくじる、チャンスを台無しにする', 'I had one chance and I blew it.', 'チャンスは一度だけだったのに、しくじった。'],
  ['fit like a glove', 'v', 'fit perfectly', 'ぴったり合う', 'This jacket fits like a glove.', 'このジャケットはぴったりだ。'],
  ['quit while sb is ahead', 'v', 'stop doing sth while still successful', 'うまくいっているうちにやめる', "You've won twice — quit while you're ahead.", '2回勝ったんだから、勝っているうちにやめときな。'],
  ['turn it around', 'v', 'change a bad situation into a good one', '状況を好転させる、立て直す', 'The new CEO managed to turn it around.', '新CEOは業績を立て直した。'],
  ["show one's hand", 'v', "reveal one's plans or intentions", '手の内を見せる', "Don't show your hand too early in negotiations.", '交渉では早く手の内を見せないこと。'],
  ['circa', 'x', 'approximately (used with dates)', '（年代について）およそ、～頃', 'The building dates from circa 1900.', 'その建物は1900年頃のものだ。', 'approx'],
  ['jazz sth up', 'v', 'make sth more exciting or attractive', '～を華やかにする、盛り上げる', "Let's jazz up these slides with some images.", '画像を入れてスライドを華やかにしよう。', 'smarten'],
  ['stick out like a sore thumb', 'v', 'be very noticeable in a bad way', '悪目立ちする', 'In a suit, he stuck out like a sore thumb.', 'スーツ姿の彼は悪目立ちしていた。'],
  ["born with a silver spoon in one's mouth", 'a', 'born into a wealthy family', '裕福な家に生まれた', 'She was born with a silver spoon in her mouth.', '彼女は裕福な家に生まれた。', 'rich'],
  ['touch-and-go', 'a', 'uncertain and risky', '予断を許さない、きわどい', "It was touch-and-go whether we'd make the flight.", '飛行機に間に合うかどうかきわどかった。', 'uncertain'],
  ['bounce', 'v', '(slang) leave', '（スラング）帰る、立ち去る', "It's late — I'm gonna bounce.", '遅いし、そろそろ帰るわ。', 'leave'],
  ['up and running', 'a', 'working and in operation', '稼働して', 'The new server is up and running.', '新しいサーバーが稼働している。'],
  ['dirty laundry', 'n', 'private matters that could cause embarrassment', '内輪の恥、人に知られたくない事情', "Don't air your dirty laundry in public.", '内輪の恥を人前でさらすな。'],
  ['rock the boat', 'v', 'cause trouble by challenging the current situation', '波風を立てる', "He doesn't want to rock the boat before his promotion.", '彼は昇進前に波風を立てたくないのだ。'],
  ['give the green light', 'v', 'give permission to go ahead', 'ゴーサインを出す', 'The board gave the green light to the project.', '取締役会はプロジェクトにゴーサインを出した。', 'permit'],
  ['set in stone', 'a', 'fixed and impossible to change', '確定して変えられない', "The schedule isn't set in stone.", 'スケジュールは確定ではない。'],
  ['backhanded compliment', 'n', 'remark that sounds like praise but is actually insulting', '嫌味を含んだ褒め言葉', "'You look good for your age' is a backhanded compliment.", '「年の割に若いね」は嫌味な褒め言葉だ。'],
  ["sing sb's praises", 'v', 'praise sb enthusiastically', '（人を）べた褒めする', 'The client keeps singing your praises.', 'クライアントが君のことをべた褒めしているよ。', 'praise'],
  ['props to sb', 'x', 'credit and respect to sb', '（人に）敬意を、～に拍手', 'Props to Lisa for organizing the event.', 'イベントを企画してくれたリサに拍手。', 'praise'],
  ['with a clean slate', 'a', 'starting again with past problems forgotten', '白紙の状態から、心機一転', "Let's start the new year with a clean slate.", '新年は心機一転でいこう。'],
  ["chip on one's shoulder", 'n', 'lingering resentment, often about unfair treatment', '恨み、ひがみ、けんか腰の態度', "He's had a chip on his shoulder since he was passed over.", '昇進を見送られて以来、彼はずっとひがんでいる。'],
  ['chop-chop', 'x', 'hurry up', '早く早く、急いで', "Chop-chop, the taxi's waiting!", '急いで、タクシーが待ってるよ！', 'hurry'],
  ['cool as a cucumber', 'a', 'extremely calm', '落ち着き払った', 'She was cool as a cucumber during the interview.', '面接中、彼女は落ち着き払っていた。', 'calm'],
  ['knuckle down', 'v', 'start working seriously', '本腰を入れる', 'Time to knuckle down and study.', '本腰を入れて勉強する時だ。'],
  ['takeaway', 'n', 'the main point to remember', '要点、学び', 'The key takeaway is to test early.', '重要な学びは、早めにテストすることだ。', 'summary'],
  ['recap', 'n', 'short summary of what was said or done', '要約、おさらい', "Here's a quick recap of yesterday's meeting.", '昨日の会議を簡単におさらいします。', 'summary'],
  ['ring a bell', 'v', 'sound familiar', '聞き覚えがある', 'Her name rings a bell.', '彼女の名前には聞き覚えがある。'],
  ['call a spade a spade', 'v', 'speak frankly and directly', '歯に衣着せずに言う、ありのままに言う', "Let's call a spade a spade: this project failed.", 'はっきり言おう、このプロジェクトは失敗した。', 'honest'],
  ['front-load sth', 'v', 'arrange for most of sth to happen at the beginning', '～を前倒しにする', 'We front-loaded the hardest tasks.', '一番難しい作業を前倒しにした。'],
  ['drip-feed sth', 'v', 'provide sth slowly in small amounts', '～を少しずつ小出しにする', 'They drip-fed information to the press.', '彼らは報道陣に情報を小出しにした。'],
  ['wild goose chase', 'n', 'a useless search or pursuit', '無駄骨、無駄な追跡', 'The error log sent us on a wild goose chase.', 'エラーログのせいで無駄骨を折った。'],
  ['spruce sth/sb up', 'v', 'make sth/sb neater or more attractive', '～をこぎれいにする', 'We spruced up the office before the client visit.', 'クライアント訪問の前にオフィスをきれいにした。', 'smarten'],
  ["walk in sb's shoes", 'v', "imagine being in sb's situation", '（人の）立場になって考える', "Try to walk in your customers' shoes.", '顧客の立場になって考えてみて。'],
  ['spin wheels', 'v', 'make effort but achieve nothing', '空回りする', "We're just spinning our wheels without clear goals.", '明確な目標がないので空回りしているだけだ。', 'stuck'],
  ['talk down to sb', 'v', 'speak to sb as if they were less intelligent', '（人を）見下して話す', "Don't talk down to new hires.", '新入社員を見下した話し方をしないで。'],
  ['full of oneself', 'a', 'too proud of oneself; self-centered', 'うぬぼれた', "Since his promotion, he's been so full of himself.", '昇進して以来、彼はすっかりうぬぼれている。'],
  ['snapshot', 'n', 'brief overview of a situation at a particular time', '（ある時点の）概況、一端', 'This report gives a snapshot of our sales.', 'このレポートで売上の概況がわかる。', 'summary'],
  ['like pulling teeth', 'a', 'extremely difficult', 'ひどく骨が折れる', 'Getting a decision from them is like pulling teeth.', '彼らから決定を引き出すのは本当に骨が折れる。', 'difficult'],
  ['pull the trigger', 'v', 'finally decide to act', '決断を下す、実行に移す', 'We need to pull the trigger on the new hire.', '新規採用について決断を下す必要がある。', 'decide'],
  ['sketchy', 'a', 'seeming dishonest or unsafe', '怪しい、危なっかしい', 'That neighborhood looks a bit sketchy at night.', 'あの地区は夜ちょっと物騒だ。', 'suspicious'],
  ['everything under the sun', 'n', 'every possible thing', 'ありとあらゆるもの', 'That store sells everything under the sun.', 'あの店はありとあらゆるものを売っている。'],
  ['go-ahead', 'n', 'permission to start', '許可、ゴーサイン', 'We got the go-ahead from legal.', '法務からゴーサインが出た。', 'permit'],
  ['ramp up sth', 'v', 'increase sth', '～を増やす、強化する', "We're ramping up production next month.", '来月から生産を増強する。'],
  ['play it by ear', 'v', 'decide how to act as things happen', '臨機応変にやる', "Let's play it by ear and see how the weather is.", '天気を見ながら臨機応変に決めよう。', 'improvise'],
  ['sugarcoat sth', 'v', 'make sth unpleasant sound better than it is', '～を（オブラートに包んで）よく見せる', "I won't sugarcoat it — sales are down.", '包み隠さず言うと、売上は落ちている。'],
  ['OCD', 'a', '(informal) extremely particular about order or cleanliness', '（口語）神経質なほど几帳面な', "I'm a bit OCD about keeping my desk tidy.", '机の整頓には少し神経質なくらいこだわる。'],
  ['two sides of the same coin', 'n', 'two different aspects of the same thing', '表裏一体', 'Risk and reward are two sides of the same coin.', 'リスクとリターンは表裏一体だ。'],
];
