// No.301–400
export default [
  ['black sheep', 'n', 'family member regarded as a disgrace', '一家の厄介者、はみ出し者', 'He was the black sheep of the family.', '彼は一家の厄介者だった。'],
  ['take sth as gospel', 'v', 'believe sth is completely true without question', '～を鵜呑みにする', "Don't take everything you read online as gospel.", 'ネットで読んだことを何でも鵜呑みにしないで。'],
  ['roll sth out', 'v', 'launch or introduce sth', '～を展開する、導入する', "We'll roll out the update next week.", '来週アップデートを展開する。', 'begin'],
  ['rough sb up', 'v', 'physically attack sb', '（人を）痛めつける、手荒く扱う', 'The guards roughed him up.', '警備員たちが彼を手荒く扱った。'],
  ['the long and the short of it', 'n', 'the main points or basic facts', '要するに、かいつまんで言えば', 'The long and the short of it is that we need more money.', '要するに、もっとお金が必要だということだ。', 'summary'],
  ['not an exact science', 'x', 'not completely precise or predictable', '厳密に割り切れるものではない', 'Estimating timelines is not an exact science.', 'スケジュールの見積もりは厳密に割り切れるものではない。'],
  ['on second thought', 'a', 'after thinking again', 'やっぱり、考え直してみると', "On second thought, let's meet tomorrow.", 'やっぱり、明日会おう。'],
  ['more art than science', 'x', 'based on intuition more than on rules or logic', '理屈よりセンスの問題', 'Hiring is more art than science.', '採用は理屈よりもセンスがものを言う。'],
  ["bite one's (own) tongue", 'v', 'stop yourself from saying what you think', '言いたいことをぐっとこらえる', 'I had to bite my tongue during the meeting.', '会議中は言いたいことをぐっとこらえた。'],
  ['under lock and key', 'a', 'kept securely locked away', '厳重に保管されて', 'The prototypes are kept under lock and key.', '試作品は厳重に保管されている。'],
  ['rough around the edges', 'a', 'not fully refined or polished', '粗削りな', 'The app is still a bit rough around the edges.', 'アプリはまだ少し粗削りだ。'],
  ['at the eleventh hour', 'a', 'at the last possible moment', '土壇場で', 'The deal was saved at the eleventh hour.', '取引は土壇場で救われた。'],
  ['over the hill', 'a', "too old; past one's best", '盛りを過ぎた', 'At 35, he felt over the hill for professional football.', '35歳の彼は、プロサッカー選手としては盛りを過ぎたと感じた。', 'old'],
  ["settle one's differences", 'v', 'resolve a disagreement', '和解する、意見の相違を解消する', 'The two founders finally settled their differences.', '2人の創業者はついに和解した。'],
  ['put in the hard yards', 'v', 'do the hard work needed for success', '地道な努力を重ねる', 'You have to put in the hard yards to get good at coding.', 'コーディングがうまくなるには地道な努力が必要だ。', 'effort'],
  ['time-sensitive', 'a', 'needing to be dealt with quickly', '急を要する、期限のある', 'This request is time-sensitive.', 'この依頼は急ぎです。'],
  ['have an eye for sth', 'v', 'be naturally good at noticing or judging sth', '～を見抜く目がある', 'She has an eye for talent.', '彼女には才能を見抜く目がある。'],
  ["play out of one's skin", 'v', 'perform far better than usual', '実力以上の力を発揮する', 'The goalkeeper played out of his skin.', 'ゴールキーパーは実力以上の活躍をした。'],
  ['throw in the towel', 'v', 'give up', '降参する、あきらめる', 'After three failed attempts, they threw in the towel.', '3度失敗して、彼らはあきらめた。'],
  ['diamond in the rough', 'n', 'person with great potential who lacks polish', '磨けば光る原石', 'That junior developer is a diamond in the rough.', 'あの若手開発者は磨けば光る原石だ。'],
  ['take the sting out of sth', 'v', 'make sth less painful or unpleasant', '～の痛みを和らげる', 'The bonus took the sting out of the long hours.', 'ボーナスで長時間労働のつらさが和らいだ。', 'soften'],
  ['shoot for the stars', 'v', 'aim very high', '高い目標を目指す', 'Shoot for the stars — the worst that happens is you land on the moon.', '高みを目指そう。最悪でも月には届く。', 'ambitious'],
  ["at the end of one's rope", 'a', 'having no patience or energy left', '我慢の限界で、万策尽きて', "I'm at the end of my rope with this printer.", 'このプリンターにはもう我慢の限界だ。'],
  ['keep sth to oneself', 'v', 'not tell anyone sth', '～を人に言わない、胸にしまっておく', 'Please keep this to yourself for now.', '今のところ、これは内緒にしておいて。', 'secret'],
  ["weigh on sb's mind", 'v', 'make sb worry', '（人の）心に重くのしかかる', 'The layoffs have been weighing on my mind.', '人員削減のことが心に重くのしかかっている。', 'worry'],
  ['table sth', 'v', '(US) postpone discussing sth; (UK) present sth for discussion', '（米）棚上げにする；（英）議題に出す', "Let's table this until next week.", 'これは来週まで棚上げにしよう。', 'postpone'],
  ['straight and narrow', 'n', 'an honest and moral way of living', 'まっとうな生き方', "He's been on the straight and narrow since leaving prison.", '出所後、彼はまっとうに暮らしている。'],
  ['pizzazz', 'n', 'energy and attractive style', '華やかさ、活気', 'The presentation needs more pizzazz.', 'プレゼンにはもっと華が必要だ。'],
  ["strike while the iron's hot", 'v', 'act quickly while an opportunity is available', '好機を逃さない（鉄は熱いうちに打て）', "Demand is high, so let's strike while the iron's hot.", '需要が高いうちに、好機を逃さず動こう。'],
  ['talk shop', 'v', 'talk about work in a social situation', '（仕事以外の場で）仕事の話をする', 'No talking shop at dinner, please.', '夕食の席で仕事の話はやめてね。'],
  ["right under sb's nose", 'a', 'very close to sb, yet unnoticed', '（人の）目の前で、すぐそばで', 'The keys were right under my nose.', '鍵はすぐ目の前にあった。'],
  ['go Dutch', 'v', 'share the cost of a meal equally', '割り勘にする', "Let's go Dutch on dinner.", '夕食は割り勘にしよう。'],
  ['long shot', 'n', 'something with little chance of success', '見込みの薄いこと', "It's a long shot, but let's apply anyway.", '見込みは薄いけど、とにかく応募しよう。'],
  ['the powers that be', 'n', 'the people in authority', 'お偉方、当局', 'The powers that be decided to cancel the project.', 'お偉方がプロジェクトの中止を決めた。'],
  ['keep sb up at night', 'v', 'worry sb a great deal', '（人を）眠れないほど悩ませる', 'What keeps you up at night as a CEO?', 'CEOとして眠れないほど気がかりなことは何ですか？', 'worry'],
  ['like two peas in a pod', 'a', 'extremely similar', '瓜二つの、そっくりな', 'The twins are like two peas in a pod.', 'その双子は瓜二つだ。'],
  ['razor-thin', 'a', 'extremely small or narrow', 'ごくわずかな', 'They won by a razor-thin margin.', '彼らはごくわずかの差で勝った。'],
  ['punchy', 'a', 'short, forceful and effective', '簡潔で力強い、パンチの効いた', 'We need a punchy headline.', 'パンチの効いた見出しが必要だ。'],
  ['lax', 'a', 'not strict or careful enough', '手ぬるい、緩い', 'Security at the event was lax.', 'イベントの警備は手ぬるかった。'],
  ['show face', 'v', 'make a brief appearance at an event', '顔を出す', "I'll show face at the party for an hour.", 'パーティーに1時間だけ顔を出すよ。'],
  ['firing on all cylinders', 'a', 'working at full power and efficiency', '絶好調で、フル回転で', 'The team is firing on all cylinders.', 'チームは絶好調だ。'],
  ['ignorance is bliss', 'x', 'not knowing sth can make you happier', '知らぬが仏', "I don't check my bank balance — ignorance is bliss.", '残高は確認しない。知らぬが仏だ。'],
  ['steady the ship', 'v', 'bring calm and stability to a difficult situation', '事態を安定させる、立て直す', "The interim CEO's job is to steady the ship.", '暫定CEOの仕事は事態を安定させることだ。'],
  ['collecting dust', 'a', 'not used for a long time', '使われずにほこりをかぶっている', 'My guitar has been collecting dust for years.', 'ギターは何年もほこりをかぶっている。'],
  ['be of two minds', 'v', 'be unable to decide between two options', '決めかねている、迷っている', "I'm of two minds about accepting the offer.", 'オファーを受けるか迷っている。', 'uncertain'],
  ['gas-guzzler', 'n', 'car that uses a lot of fuel', '燃費の悪い車', 'I traded my gas-guzzler for a hybrid.', '燃費の悪い車をハイブリッド車に買い替えた。'],
  ['so on and so forth', 'x', 'and other similar things', '～などなど', 'We discussed budgets, timelines, and so on and so forth.', '予算やスケジュールなどなどについて話した。'],
  ['bread and butter', 'n', 'main source of income; the basic essentials', '生計の手段、基本', 'Consulting is our bread and butter.', 'コンサルティングが私たちの主な収入源だ。'],
  ["straw that broke the camel's back", 'n', 'the final small problem that causes a collapse', '我慢の限界を超えさせる最後の一押し', "The pay cut was the straw that broke the camel's back.", '減給が最後の一押しとなった。'],
  ['nag (sb)', 'v', 'criticize or complain to sb repeatedly', '（人に）うるさく小言を言う', 'My mom keeps nagging me to call more often.', '母がもっと電話しなさいとうるさく言ってくる。'],

  ['married to the idea', 'a', 'strongly attached to an idea', 'その考えに固執して', "Don't get too married to the idea; we may need to pivot.", 'その考えに固執しすぎないで。方向転換が必要かも。'],
  ['make or break sth/sb', 'v', 'decide whether sth/sb succeeds or fails', '～の成否を決める', 'This deal could make or break the company.', 'この取引が会社の命運を分けるかもしれない。'],
  ['trailblazer', 'n', 'innovator or pioneer', '先駆者', 'She was a trailblazer for women in tech.', '彼女はテック業界の女性の先駆者だった。'],
  ['take sth as read', 'v', 'treat sth as accepted or understood without discussing it', '～を了承済みとみなす', 'We can take the minutes as read.', '議事録は確認済みとしてよいでしょう。'],
  ['soften the blow', 'v', 'make bad news less painful', '衝撃を和らげる', 'They offered a bonus to soften the blow of the pay freeze.', '昇給凍結の衝撃を和らげるため、ボーナスが提示された。', 'soften'],
  ["put one's money where one's mouth is", 'v', 'act in a way that supports what you say', '有言実行する', 'If you believe in it, put your money where your mouth is.', '信じているなら、言葉だけでなく行動で示して。'],
  ['shell-shocked', 'a', 'so shocked that one cannot act', '呆然とした', 'Staff were shell-shocked after the announcement.', '発表の後、社員は呆然としていた。'],
  ['hindsight is 20/20', 'x', "it's easy to see the right choice after the event", '後からなら何とでも言える', "Hindsight is 20/20 — we couldn't have known.", '後からなら何とでも言える。当時はわかりようがなかった。'],
  ['show sb the ropes', 'v', 'teach sb how to do a job', '（人に）仕事のやり方を教える', 'Mark will show you the ropes on your first day.', '初日はマークが仕事のやり方を教えてくれるよ。'],
  ['put two and two together', 'v', 'work out a conclusion from the available facts', '状況から推測する、ピンとくる', 'I put two and two together when I saw them leave together.', '二人が一緒に帰るのを見てピンときた。'],
  ['red herring', 'n', 'something that distracts attention from the real issue', '本題から注意をそらすもの', 'The network error was a red herring.', 'ネットワークエラーは本筋とは関係なかった。'],
  ['take stock of sth', 'v', 'carefully assess a situation', '～を見直す、状況を評価する', "Let's take stock of where we are.", '現状を見直してみよう。', 'check'],
  ['pull some strings', 'v', 'use personal connections to get what you want', 'コネを使う、裏で手を回す', 'Can you pull some strings to get us tickets?', 'コネを使ってチケットを取ってもらえない？'],
  ['call the shots', 'v', 'be the person who makes the decisions', '決定権を握る、仕切る', "Who's calling the shots on this project?", 'このプロジェクトは誰が仕切っているの？', 'decide'],
  ['be-all and end-all', 'n', 'the most important thing', '最も重要なもの、すべて', "Salary isn't the be-all and end-all.", '給料がすべてではない。', 'important'],
  ['a few sandwiches short of a picnic', 'a', '(humorous) not very intelligent', '（おどけて）ちょっと頭が足りない', "He's nice, but a few sandwiches short of a picnic.", '彼はいい人だけど、ちょっと抜けている。'],
  ['on cloud nine', 'a', 'extremely happy', '有頂天で', "She's been on cloud nine since the promotion.", '昇進して以来、彼女は有頂天だ。', 'happy'],
  ['once-in-a-lifetime', 'a', 'extremely rare; happening only once', '一生に一度の', "It's a once-in-a-lifetime opportunity.", '一生に一度のチャンスだ。'],
  ['ask for the world', 'v', 'ask for sth unreasonably big or difficult', '無理な要求をする', "I'm not asking for the world — just a day off.", '無理なことは言ってない、1日休みが欲しいだけだ。'],
  ['snappy', 'a', 'irritable and quick to speak sharply', 'とげとげしい、つっけんどんな', "Sorry I was snappy earlier — I'm tired.", 'さっきはつっけんどんでごめん、疲れてて。'],
  ['under the table', 'a', 'secretly and often illegally', '裏で、闇で', 'He was paid under the table.', '彼は裏で給料を受け取っていた。', 'secretly'],
  ['smooth things over', 'v', 'make a problem or disagreement less serious', '事を丸く収める', 'I called the client to smooth things over.', '事を丸く収めるためにクライアントに電話した。'],
  ['David and Goliath', 'a', 'between a small, weak side and a big, powerful one', '小さな者と巨人の戦い（の）', "It's a David and Goliath battle between a startup and a tech giant.", 'スタートアップと巨大IT企業の、まさに小が大に挑む戦いだ。'],
  ['sight for sore eyes', 'n', 'a person or thing you are very glad to see', '見てうれしいもの・人', "You're a sight for sore eyes!", '会えて本当にうれしいよ！'],
  ['tempest in a teapot', 'n', 'a lot of fuss about something unimportant', 'コップの中の嵐、空騒ぎ', 'The controversy was a tempest in a teapot.', 'その騒動は空騒ぎにすぎなかった。'],
  ['sick', 'a', '(slang) excellent; really cool', '（スラング）最高の、すごい', 'That skateboard trick was sick!', '今のスケボーの技、すごすぎ！'],
  ["all's well that ends well", 'x', "if the result is good, earlier problems don't matter", '終わりよければすべてよし', "We missed a deadline, but all's well that ends well.", '締め切りは逃したけど、終わりよければすべてよしだ。'],
  ['selective memory', 'n', 'remembering only what suits you', '都合のいい記憶', 'He has a selective memory when it comes to his promises.', '彼は約束に関しては都合のいいことしか覚えていない。'],
  ['sell oneself short', 'v', "underestimate one's own abilities", '自分を過小評価する', "Don't sell yourself short — you're qualified.", '自分を過小評価しないで。資格は十分あるよ。'],
  ['be in for the long haul', 'v', 'be committed for a long period', '長期戦の覚悟がある', "We're in this for the long haul.", '私たちは長期戦の覚悟でやっている。'],
  ['speaks for itself', 'v', 'is clear and needs no further explanation', '説明不要だ、一目瞭然だ', 'The data speaks for itself.', 'データが物語っている。'],
  ['pump iron', 'v', 'lift weights', '筋トレ（ウェイトトレーニング）をする', 'He pumps iron at the gym every morning.', '彼は毎朝ジムで筋トレしている。'],
  ['move heaven and earth', 'v', 'do everything possible to achieve sth', 'あらゆる手を尽くす', "I'll move heaven and earth to get you there on time.", '間に合うように、あらゆる手を尽くすよ。', 'effort'],
  ['throw sb a bone', 'v', 'give sb a small reward to keep them satisfied', '（人を）なだめるために少し譲る', 'Management threw us a bone with an extra day off.', '経営陣は休みを1日追加して私たちをなだめた。'],
  ['full steam ahead', 'a', 'with maximum speed and energy', '全速力で、全力で', "Once approved, it's full steam ahead.", '承認されたら全速力で進める。'],
  ['picture this', 'x', 'imagine this', '想像してみて', 'Picture this: no more meetings on Fridays.', '想像してみて。金曜日は会議なし。'],
  ['ship-shape', 'a', 'neat and in good order', 'きちんと整頓された', 'Get the office ship-shape before the inspection.', '検査の前にオフィスをきちんと片付けて。', 'smarten'],
  ['run riot', 'v', 'behave wildly; spread out of control', '暴れ回る、はびこる', 'Weeds have run riot in the garden.', '庭に雑草がはびこっている。'],
  ['kudos', 'n', 'praise and credit for an achievement', '称賛、賛辞', 'Kudos to the support team for their hard work.', 'サポートチームの頑張りに称賛を。', 'praise'],
  ['stars are aligned', 'x', 'all the conditions are favorable', '条件がすべて整っている', 'The stars are aligned for a successful launch.', 'ローンチ成功の条件がすべて整っている。'],
  ['carry a tune', 'v', 'sing in tune', '音程をはずさずに歌う', "I can't carry a tune to save my life.", '私はどうしても音痴だ。'],
  ['the Midas touch', 'n', 'the ability to make money from everything one does', '何でも成功させる（金にする）才能', 'That investor has the Midas touch.', 'あの投資家は何をやっても儲かる。'],
  ['nothing to sneeze at', 'x', 'not to be dismissed; significant', '侮れない、ばかにできない', 'A 5% raise is nothing to sneeze at.', '5%の昇給は侮れない。'],
  ['walk on eggshells', 'v', 'be very careful not to upset sb', '腫れ物に触るように振る舞う', 'Everyone walks on eggshells around the new director.', '新しい部長の前では皆が腫れ物に触るように振る舞っている。'],
  ['walk on sunshine', 'v', 'feel extremely happy', 'うきうきしている', "Since the wedding, she's been walking on sunshine.", '結婚式以来、彼女はうきうきしている。', 'happy'],
  ['play on words', 'n', 'a pun', '言葉遊び、だじゃれ', 'The product name is a play on words.', '製品名は言葉遊びになっている。'],
  ['scratch the surface', 'v', 'deal with only a small part of sth', '表面をかじる、ほんの一部に触れる', 'This report only scratches the surface.', 'このレポートはほんの表面をなぞっているにすぎない。'],
  ['staycation', 'n', 'vacation spent at or near home', '自宅や近場で過ごす休暇', "We're doing a staycation this summer.", '今年の夏は近場で休暇を過ごす。'],
  ['stretch goal/target', 'n', 'a deliberately ambitious target', '背伸びした目標、挑戦的な目標', 'Our stretch goal is one million users.', '背伸びした目標は100万ユーザーだ。', 'ambitious'],
  ['on the way out', 'a', 'becoming obsolete; about to leave a job', '廃れかけて；辞めかけて', 'Fax machines are on the way out.', 'ファックスは廃れつつある。'],
];
