// No.101–200
export default [
  ['gold standard', 'n', 'the best example, used to judge all others', '最高水準、模範', 'This textbook is the gold standard for beginners.', 'この教科書は初心者向けの最高峰だ。'],
  ['kick sth off', 'v', 'start sth', '～を開始する', "Let's kick off the meeting with a quick update.", '簡単な近況報告から会議を始めましょう。', 'begin'],
  ["on one's last legs", 'a', 'close to the end of its life or usefulness', '寿命が近い、今にも壊れそうな', 'My car is on its last legs.', '私の車はもう寿命が近い。'],
  ['pluck sth out of thin air', 'v', 'make up sth, such as a number, without any basis', '（根拠なく）でっちあげる、適当に言う', 'He plucked that figure out of thin air.', '彼はその数字を根拠なく適当に出した。'],
  ['make a move', 'v', 'leave; (also) take action', '（その場を）おいとまする；行動を起こす', "It's late — I should make a move.", '遅くなったし、そろそろ帰らなきゃ。', 'leave'],
  ['selling point', 'n', 'feature that makes sth attractive to buyers', 'セールスポイント、売り', 'Battery life is its main selling point.', 'バッテリー持ちが一番の売りだ。'],
  ['all-in on sth', 'a', 'totally committed to sth', '～に全力を注いで', 'The company is all-in on AI.', 'その会社はAIに全力を注いでいる。'],
  ['light at the end of the tunnel', 'n', 'sign that a difficult period is about to end', '苦境の終わりの兆し、光明', "After months of overtime, there's finally light at the end of the tunnel.", '何か月もの残業の末、ようやく出口が見えてきた。'],
  ['party animal', 'n', 'someone who loves going to parties', 'パーティー好き、遊び好き', 'He was a real party animal in college.', '彼は大学時代、かなりのパーティー好きだった。'],
  ['could hear a pin drop', 'x', 'it was so silent that the tiniest sound was audible', 'しーんと静まり返っていた', 'When she announced the layoffs, you could hear a pin drop.', '彼女が人員削減を発表すると、場はしーんと静まり返った。'],
  ['wordy', 'a', 'using more words than necessary', '言葉数が多すぎる、冗長な', 'Your email is a bit wordy — try to shorten it.', '君のメールは少し冗長だから、短くしてみて。'],
  ['surefire', 'a', 'certain to succeed', '確実な、必ずうまくいく', "There's no surefire way to get rich.", '確実に金持ちになる方法なんてない。'],
  ['up in the air', 'a', 'not yet decided', '未定の、宙に浮いた', 'Our travel plans are still up in the air.', '旅行の予定はまだ未定だ。', 'uncertain'],
  ['worth a shot', 'a', 'worth trying', 'やってみる価値がある', "It might not work, but it's worth a shot.", 'うまくいかないかもしれないが、試す価値はある。'],
  ['character', 'n', 'an interesting, unusual or funny person', '個性的な人、おもしろい人', 'Our new neighbor is quite a character.', '新しいお隣さんはかなりの個性派だ。'],
  ['sharp', 'a', 'intelligent and quick to understand', '頭の切れる、鋭い', "She's really sharp — she spotted the flaw immediately.", '彼女は本当に頭が切れる。すぐに欠陥を見抜いた。'],
  ['burning desire', 'n', 'a very strong wish', '強い願望、熱望', 'He has a burning desire to start his own company.', '彼は自分の会社を起こしたいという強い願望を持っている。'],
  ['fly on the wall', 'n', 'someone who secretly watches a private situation', '（気づかれずに）こっそり見聞きする人', "I'd love to be a fly on the wall in that board meeting.", 'あの取締役会をこっそりのぞいてみたいものだ。'],
  ['gibberish', 'n', 'meaningless or unintelligible language', 'わけのわからない言葉、ちんぷんかんぷん', 'The error message was complete gibberish to me.', 'そのエラーメッセージは私にはちんぷんかんぷんだった。'],
  ['egg sb on', 'v', 'urge sb to do sth, usually unwise', '（人を）けしかける、そそのかす', 'His friends egged him on to jump into the river.', '友人たちが彼に川へ飛び込めとけしかけた。'],
  ['face-time', 'n', 'time spent talking with sb in person', '対面で話す時間', 'Remote work means less face-time with the team.', 'リモートワークだとチームとの対面時間が減る。'],
  ['pull an all-nighter', 'v', 'stay awake all night working or studying', '徹夜する', 'I pulled an all-nighter to finish the report.', 'レポートを終わらせるために徹夜した。'],
  ['leave it there', 'v', 'end the discussion at this point', '（話を）ここまでにする', "Let's leave it there for today.", '今日はここまでにしましょう。'],
  ['down-to-earth', 'a', 'practical, realistic and easy to relate to', '気取らない、現実的な', "Despite being famous, she's very down-to-earth.", '有名なのに、彼女はとても気さくだ。'],
  ['jump the gun', 'v', 'act too early', 'フライングする、早まった行動をとる', "Let's not jump the gun before the results are in.", '結果が出る前に早まったことはしないでおこう。'],
  ['back sth up', 'v', 'support a claim with evidence', '（主張を）裏付ける', 'Can you back that up with data?', 'それをデータで裏付けられる？'],
  ['get a kick out of sth', 'v', 'really enjoy sth', '～を大いに楽しむ', 'I get a kick out of solving puzzles.', 'パズルを解くのが楽しくてたまらない。'],
  ['hands down', 'a', 'definitely; without question', '文句なしに、間違いなく', 'This is hands down the best pizza in town.', 'これは間違いなく町で一番のピザだ。'],
  ['dumb sth down', 'v', 'make sth simpler, often too simple', '（過度に）わかりやすくする、レベルを下げる', "Don't dumb it down too much — they're experts.", '簡単にしすぎないで。相手は専門家だから。'],
  ['on the fly', 'a', 'while doing sth, without planning in advance', 'その場で、臨機応変に', 'We had to change the plan on the fly.', 'その場で計画を変えなければならなかった。', 'improvise'],
  ['fishy', 'a', 'seeming suspicious or dishonest', '怪しい、うさんくさい', 'Something fishy is going on with these invoices.', 'この請求書、何か怪しい。', 'suspicious'],
  ['give or take', 'x', 'approximately, plus or minus a little', '～前後、だいたい', "It'll take two hours, give or take.", '2時間前後かかるだろう。', 'approx'],
  ['educated guess', 'n', 'estimate based on knowledge and experience', '知識に基づく推測', "I'd make an educated guess that it's a memory leak.", '知識からの推測だけど、メモリリークだと思う。', 'guess'],
  ['hit a wall', 'v', 'reach a point where no more progress is possible', '壁にぶつかる、行き詰まる', 'I hit a wall with my research.', '研究が行き詰まった。', 'stuck'],
  ["on sb's radar", 'a', 'being noticed or considered by sb', '（人の）視野に入って、検討対象に', 'Is this issue on your radar?', 'この問題、把握してる？'],
  ['broken record', 'n', 'someone who keeps repeating the same thing', '同じことばかり言う人', 'I sound like a broken record, but please lock your screens.', '何度も同じことを言うようだけど、画面ロックをしてください。'],
  ['stoked', 'a', 'very excited and happy', 'すごく楽しみな、テンションが上がった', "I'm so stoked about the trip!", '旅行が楽しみすぎる！', 'excited'],
  ['sooner rather than later', 'a', 'soon, without delay', '早めに、できるだけ早く', 'We should fix this sooner rather than later.', 'これは早めに直したほうがいい。'],
  ["get one's story straight", 'v', "make sure one's account of events is consistent", '話のつじつまを合わせる', 'They met beforehand to get their story straight.', '彼らは事前に会って話のつじつまを合わせた。'],
  ['reinvent the wheel', 'v', 'waste effort creating sth that already exists', '一から作り直す（無駄な努力をする）', "Let's use an existing library instead of reinventing the wheel.", '車輪の再発明はやめて既存のライブラリを使おう。'],
  ['hear through the grapevine', 'v', 'learn sth as a rumor', '噂で聞く', "I heard through the grapevine that she's leaving.", '噂で彼女が辞めると聞いた。'],
  ['fired up', 'a', 'highly worked up; angry or very enthusiastic', '熱くなった、興奮した', 'He got really fired up about the unfair decision.', '彼は不公平な決定にすっかり熱くなった。'],
  ['crash course', 'n', 'short, intensive course or explanation', '短期集中講座、手短な説明', 'I took a crash course in Python.', 'Pythonの短期集中講座を受けた。'],
  ['settle in', 'v', 'get used to a new place or job', '（新しい環境に）慣れる、落ち着く', 'How are you settling in at the new office?', '新しいオフィスには慣れた？'],
  ['worked up', 'a', 'upset, anxious or overexcited', '動揺した、カッカした', "Don't get so worked up about it.", 'そんなにカッカしないで。'],
  ['control freak', 'n', 'person who wants to control everything around them', '何でも仕切りたがる人', 'My boss is a total control freak.', '上司は何でも自分で仕切らないと気がすまない人だ。'],
  ['needle in a haystack', 'n', 'something almost impossible to find', '見つけるのが極めて難しいもの', 'Finding the bug in this legacy code is like looking for a needle in a haystack.', 'このレガシーコードでバグを探すのは、干し草の山から針を探すようなものだ。'],
  ['put up with sth', 'v', 'tolerate sth unpleasant', '～を我慢する', "I can't put up with this noise any longer.", 'もうこの騒音には我慢できない。'],
  ['put sb on the spot', 'v', 'ask sb a difficult or embarrassing question without warning', '（人を）困らせる質問をして答えを迫る', "Sorry to put you on the spot, but what's your opinion?", '急に振って悪いけど、君の意見は？'],
  ['wasted', 'a', '(slang) very drunk', '（スラング）泥酔した', 'He got completely wasted at the party.', '彼はパーティーで泥酔した。'],

  ['ego-boosting', 'a', 'making sb feel more confident', '自信をつけてくれる、自尊心をくすぐる', 'Winning the award was a real ego-boosting moment.', '受賞は本当に自信につながる瞬間だった。'],
  ['carry the team', 'v', 'be the main reason a team succeeds', 'チームを（一人で）引っ張る', 'She basically carried the team this quarter.', '今期は彼女がほぼ一人でチームを引っ張った。'],
  ['down in the dumps', 'a', 'sad and depressed', '落ち込んで、ふさぎ込んで', "He's been down in the dumps since the breakup.", '彼は別れてからずっと落ち込んでいる。', 'sad'],
  ['big fan of sth', 'n', 'someone who likes sth a lot', '～の大ファン、～が大好きな人', "I'm not a big fan of open-plan offices.", 'オープンオフィスはあまり好きじゃない。'],
  ['backfire', 'v', 'have the opposite effect to what was intended', '裏目に出る', 'His plan to save money backfired.', '彼の節約計画は裏目に出た。'],
  ['iffy', 'a', 'uncertain or of doubtful quality', '微妙な、あやしい', 'The Wi-Fi here is a bit iffy.', 'ここのWi-Fiはちょっと不安定だ。', 'uncertain'],
  ['go down well', 'v', 'be received positively', '好評を得る、受けがいい', "The new policy didn't go down well with staff.", '新方針は社員にあまり受けがよくなかった。'],
  ['step up', 'v', 'take on more responsibility when it is needed', '（必要なときに）責任を引き受ける、奮起する', 'When the manager left, Tom stepped up.', 'マネージャーが辞めたとき、トムが率先して役目を引き受けた。'],
  ['inch-perfect', 'a', 'extremely precise', '寸分の狂いもない', 'Her pass was inch-perfect.', '彼女のパスは寸分の狂いもなかった。'],
  ["keep one's head", 'v', 'stay calm in a difficult situation', '冷静さを失わない', 'She kept her head during the crisis.', '危機の中でも彼女は冷静だった。', 'calm'],
  ['rule of thumb', 'n', 'general guideline based on experience rather than precision', '経験則、目安', 'As a rule of thumb, save 10% of your income.', '目安として、収入の10%は貯金しよう。'],
  ['crack (sb) up', 'v', '(make sb) laugh a lot', '大笑いする／（人を）大笑いさせる', 'His impressions always crack me up.', '彼のモノマネにはいつも大笑いさせられる。'],
  ['take it the wrong way', 'v', 'misunderstand sth and be offended', '悪く取る、誤解する', "Don't take it the wrong way, but your slides are too busy.", '悪く取らないでほしいんだけど、スライドが詰め込みすぎだよ。'],
  ['give some context', 'v', 'provide background information', '背景を説明する', 'Let me give some context before the demo.', 'デモの前に少し背景を説明させてください。'],
  ['drama queen', 'n', 'someone who overreacts to everything', '大げさに騒ぐ人', "Stop being such a drama queen — it's just a scratch.", '大げさに騒がないで、ただのかすり傷だよ。'],
  ['go all-out', 'v', 'make the greatest possible effort, often excessively', '全力を尽くす、（派手に）やりすぎる', 'They went all-out for the holiday party.', '彼らは年末パーティーに全力を注いだ。', 'effort'],
  ['cover all bases', 'v', 'prepare for every possible situation', 'あらゆる事態に備える', 'We tested on every browser to cover all bases.', 'あらゆる事態に備えて全ブラウザでテストした。'],
  ['by the book', 'a', 'strictly following the rules', '規則どおりに', 'Our auditor does everything by the book.', 'うちの監査人は何でも規則どおりにやる。'],
  ['think it through', 'v', 'consider sth carefully before deciding', 'よく考える、熟考する', 'Take a day to think it through.', '1日かけてよく考えて。'],
  ['heads-up', 'n', 'advance warning or notice', '事前の知らせ、予告', 'Thanks for the heads-up about the outage.', '障害について事前に知らせてくれてありがとう。'],
  ['call it (a day)', 'v', 'stop working for the rest of the day', '（今日の仕事を）切り上げる', "It's 7 — let's call it a day.", '7時だし、今日はこれで切り上げよう。'],
  ['in a roundabout way', 'a', 'indirectly', '遠回しに', 'She told me in a roundabout way that I was wrong.', '彼女は遠回しに私が間違っていると言った。'],
  ['under the weather', 'a', 'slightly ill', '体調がすぐれない', "I'm feeling a bit under the weather today.", '今日はちょっと体調がすぐれない。'],
  ["drag one's feet", 'v', 'delay doing sth deliberately', '（わざと）ぐずぐずする、先延ばしにする', 'The vendor is dragging its feet on the contract.', 'ベンダーは契約をなかなか進めようとしない。', 'postpone'],
  ['clear the air', 'v', 'resolve tension or a misunderstanding by talking openly', 'わだかまりを解く', 'We had a chat to clear the air.', 'わだかまりを解くために話し合った。'],
  ['guesstimate', 'n', 'estimate based mostly on guessing', '当て推量の見積もり、ざっくりした概算', "This is just a guesstimate, so don't quote me.", 'これはざっくりした見積もりだから、引用しないでね。', 'guess'],
  ['dig deep', 'v', 'make a great effort, using all your resources', '底力を出す、もう一踏ん張りする', "We'll need to dig deep to hit the deadline.", '締め切りに間に合わせるには底力を出す必要がある。', 'effort'],
  ['bells and whistles', 'n', 'extra features that are attractive but unnecessary', '余計な付加機能、おまけ', "I don't need all the bells and whistles — just a basic phone.", '余計な機能はいらない、基本的な電話で十分だ。'],
  ['spot-on', 'a', 'exactly right', 'ドンピシャの、まさにその通りの', 'Your analysis was spot-on.', '君の分析はドンピシャだった。'],
  ["sb's cup of tea", 'n', 'something sb likes', '（人の）好み', "Jazz isn't really my cup of tea.", 'ジャズはあまり好みじゃない。'],
  ['look sharp', 'v', 'look smart and well-dressed', 'きちんとした身なりをしている、キマっている', 'You look sharp in that suit.', 'そのスーツ、キマってるね。'],
  ['neck and neck', 'a', 'very close in a competition', '接戦で、互角で', 'The two candidates are neck and neck in the polls.', '2人の候補は世論調査で接戦だ。'],
  ['mind-numbing', 'a', 'extremely boring', 'ひどく退屈な', 'Data entry is mind-numbing work.', 'データ入力は気が遠くなるほど退屈な仕事だ。', 'boring'],
  ['tell it like it is', 'v', 'speak honestly, even if it is unpleasant', 'ありのままに言う、歯に衣着せずに言う', 'I like her because she tells it like it is.', '彼女はずばずば本音を言うから好きだ。', 'honest'],
  ['game-changer', 'n', 'something that completely transforms a situation', '状況を一変させるもの', 'Cloud computing was a game-changer for startups.', 'クラウドはスタートアップにとって画期的なものだった。'],
  ['borrow sb', 'v', '(informal) ask sb to help you for a short time', '（人を）ちょっと借りる', 'Can I borrow you for five minutes?', '5分だけ時間をもらえる？'],
  ['look up to sb', 'v', 'admire and respect sb', '（人を）尊敬する', "I've always looked up to my older sister.", 'ずっと姉を尊敬してきた。'],
  ['killing it', 'a', 'doing extremely well', '絶好調で、すごくうまくやって', "You're killing it with these sales numbers!", 'この売上、絶好調だね！'],
  ["make it up as one goes along", 'v', 'decide what to do as you go, without a plan', '行き当たりばったりでやる', 'Nobody had a plan; we just made it up as we went along.', '誰も計画がなく、行き当たりばったりでやった。', 'improvise'],
  ['bounce ideas off sb', 'v', 'share ideas with sb to get their opinion', '（人に）アイデアをぶつけて意見をもらう', 'Can I bounce some ideas off you?', 'ちょっとアイデアを聞いてもらえる？'],
  ['bad influence', 'n', 'someone or something that encourages bad behavior', '悪影響を与える人・もの', 'Her friends are a bad influence on her.', '彼女の友人たちは彼女に悪影響を与えている。'],
  ['pushy', 'a', 'too forceful and persistent in getting what you want', '押しの強い、強引な', 'The salesman was really pushy.', 'その営業マンはとても強引だった。'],
  ['steal', 'n', 'something bought for a very low price', '掘り出し物、格安品', 'At $20, this jacket was a steal.', 'このジャケットが20ドルなんて掘り出し物だった。'],
  ['wrap sth up', 'v', 'finish or conclude sth', '～を終える、締めくくる', "Let's wrap up the meeting.", '会議を締めくくりましょう。', 'finish'],
  ['not add up', 'v', 'not make sense; seem inconsistent', 'つじつまが合わない', "His explanation just doesn't add up.", '彼の説明はどうもつじつまが合わない。'],
  ['destroyed', 'a', '(informal) extremely upset or exhausted', '（口語）打ちのめされた、ボロボロの', 'I was destroyed when my team lost the final.', '決勝で負けて打ちのめされた。', 'sad'],
  ['not too far off (sth)', 'a', 'close to sth, such as a number', '（数値などが）そう遠くない、近い', "Your estimate wasn't too far off.", '君の見積もりは大きく外れていなかった。'],
  ['heart and soul', 'n', 'the most central and essential part', '核心、中心（となる人・もの）', "She's the heart and soul of the team.", '彼女はチームの要だ。', 'important'],
  ['look on the bright side', 'v', 'focus on the positive aspects', '明るい面を見る、前向きに考える', 'Look on the bright side — at least no one was hurt.', '前向きに考えよう。少なくとも誰もけがをしなかった。'],
  ['101', 'n', 'the basic introduction to a subject', '（～の）基礎、入門', "This is Marketing 101 — know your customer.", 'これはマーケティングの基本中の基本、顧客を知ることだ。'],
];
