// No.001–100  [見出し語, 品詞(v/a/n/x), 英語の言い換え, 和訳, 例文, 例文和訳, 類義グループ(任意)]
export default [
  ['low-key', 'a', 'understated and modest; (slang) secretly', '控えめな、目立たない；（スラング）ひそかに', "Let's keep the party low-key — just a few close friends.", 'パーティーは控えめにしよう。親しい友達数人だけで。'],
  ['drive sb up the wall', 'v', 'irritate sb enormously', '（人を）ひどくイライラさせる', 'The constant notifications are driving me up the wall.', '鳴りやまない通知に本当にイライラさせられる。', 'annoy'],
  ['black and white', 'a', 'completely clear, with no room for doubt', '白黒はっきりした、明確な', "The rules aren't always black and white.", 'ルールはいつも白黒はっきりしているわけではない。', 'clear'],
  ['sloppy', 'a', 'done without enough care or attention', 'ずさんな、いい加減な', 'His code review was sloppy and missed several bugs.', '彼のコードレビューはずさんで、バグをいくつも見逃した。'],
  ['kick sb out', 'v', 'make sb leave a place or group', '（人を）追い出す', 'They kicked him out of the bar for being rude.', '彼は失礼な態度をとってバーから追い出された。'],
  ['over the top', 'a', 'excessive or exaggerated', 'やりすぎの、大げさな', 'The decorations were a bit over the top for a small meeting.', '小さな会議にしては飾り付けが少しやりすぎだった。', 'excess'],
  ['ancient', 'a', '(informal) extremely old', '（口語）ものすごく古い', 'My laptop is ancient — it still runs Windows 7.', '僕のノートPCは骨董品並みに古くて、まだWindows 7だ。', 'old'],
  ['watch out for sth/sb', 'v', 'stay alert and careful about sth/sb', '～に気をつける、用心する', 'Watch out for typos in the final draft.', '最終稿の誤字には気をつけて。'],
  ['figure sth out', 'v', 'come to understand or solve sth', '～を理解する、解決策を見つける', 'I finally figured out why the build was failing.', 'ビルドが失敗する原因がやっとわかった。', 'understand'],
  ['slack off', 'v', 'put in less effort than usual', '怠ける、手を抜く', "Don't slack off just because the boss is away.", '上司がいないからといって手を抜くな。'],
  ['overpaid', 'a', 'receiving more money than one deserves', '給料をもらいすぎの', 'Some executives are hugely overpaid.', '一部の経営者はとんでもなく高給をもらいすぎている。'],
  ['better off', 'a', 'in a more advantageous situation', '（前より）良い状況にある、～したほうがいい', "You'd be better off asking her directly.", '彼女に直接聞いたほうがいいよ。'],
  ['grab sth', 'v', 'quickly get or take sth', '（さっと）～を取る、手に入れる', "Let's grab a coffee before the meeting.", '会議の前にコーヒーでも買っていこう。', 'obtain'],
  ['take sth out of context', 'v', 'distort the meaning of sth by ignoring the situation around it', '～を文脈から切り離して解釈する', 'The journalist took my comment out of context.', '記者は私の発言を文脈から切り離して報じた。'],
  ['freebie', 'n', 'something given away at no cost', '無料のもの、景品', 'We got lots of freebies at the tech conference.', 'テックカンファレンスで無料グッズをたくさんもらった。'],
  ['clear-cut', 'a', 'clearly defined and easy to decide about', '明確な、はっきりした', "There's no clear-cut answer to this question.", 'この問題に明確な答えはない。', 'clear'],
  ['cut sb off', 'v', 'interrupt sb so they cannot finish speaking', '（人の）話をさえぎる', "Sorry to cut you off, but we're out of time.", '話の途中ですみませんが、時間切れです。'],
  ['gray area', 'n', 'situation where right and wrong are not clearly defined', 'グレーゾーン、どっちつかずの領域', 'Using AI-generated images is still a legal gray area.', 'AI生成画像の利用は、法的にはまだグレーゾーンだ。'],
  ['fiddly', 'a', 'intricate and awkward to handle', '細かくて扱いにくい、面倒な', 'Replacing the battery is a bit fiddly.', 'バッテリー交換はちょっと細かくて面倒だ。', 'difficult'],
  ['crystal-clear', 'a', 'perfectly clear and impossible to misunderstand', '非常に明白な、明快な', 'Let me make this crystal-clear: no deploys on Friday.', 'はっきりさせておくけど、金曜日のデプロイは禁止だ。', 'clear'],
  ['downtime', 'n', 'time spent resting rather than working', '休息時間、くつろぐ時間（※ITでは停止時間）', 'I need some downtime after this project.', 'このプロジェクトが終わったら少し休みが欲しい。'],
  ['check sth out', 'v', 'look at or visit sth to find out more about it', '～を調べる、見てみる', 'You should check out the new café downtown.', '街の新しいカフェ、行ってみるといいよ。'],
  ['get it', 'v', 'understand', 'わかる、理解する', 'Oh, now I get it — the bug only happens on Safari.', 'ああ、やっとわかった。バグはSafariでだけ起きるんだ。', 'understand'],
  ['hold sth/sb up', 'v', 'delay sth/sb', '～を遅らせる、引き止める', "Sorry I'm late — I got held up in traffic.", '遅れてごめん、渋滞につかまってた。'],
  ['legit', 'a', '(slang) genuine and proper', '（スラング）本物の、ちゃんとした', 'Is this website legit or a scam?', 'このサイトはちゃんとしたもの？それとも詐欺？'],
  ['catch up', 'v', 'meet and tell each other recent news', '近況を報告し合う', "Let's grab lunch and catch up next week.", '来週ランチでもして近況報告しよう。'],
  ['hyped', 'a', 'very excited', 'すごく興奮した、盛り上がった', "Everyone's hyped about the new release.", 'みんな新リリースにすごく盛り上がっている。', 'excited'],
  ['attention-seeking', 'a', 'acting deliberately to make others notice you', '目立ちたがりの、かまってほしがる', 'His attention-seeking posts are getting tiresome.', '彼の目立ちたがりの投稿にはうんざりしてきた。'],
  ['gonna do', 'x', '(informal) going to do', '（口語）～するつもり（going to）', "I'm gonna finish this tonight.", '今夜これを終わらせるつもりだ。'],
  ['get into sth', 'v', 'start to become interested in sth', '～にハマる、興味を持ち始める', 'I got into rock climbing last year.', '去年ボルダリングにハマった。'],
  ["have butterflies in one's stomach", 'v', 'feel nervous', '（緊張で）そわそわする、ドキドキする', 'I always have butterflies in my stomach before a presentation.', 'プレゼンの前はいつも緊張でドキドキする。'],
  ['cut corners', 'v', 'do sth the quickest or cheapest way, sacrificing quality', '手抜きをする、（費用・手間を）切り詰める', "We can't cut corners on security.", 'セキュリティで手抜きはできない。'],
  ['pretty much', 'x', 'almost; nearly', 'ほとんど、ほぼ', 'The project is pretty much done.', 'プロジェクトはほぼ終わっている。'],
  ['big deal', 'n', 'something very important', '重大なこと、大したこと', "Don't worry, it's not a big deal.", '心配しないで、大したことじゃないよ。', 'important'],
  ['get the ball rolling', 'v', 'start an activity or process', '（物事を）始める、口火を切る', "Let's get the ball rolling with a quick intro.", '簡単な自己紹介から始めましょう。', 'begin'],
  ['spot sth/sb', 'v', 'notice or see sth/sb', '～を見つける、～に気づく', "Good catch — I didn't spot that typo.", 'よく見つけたね。その誤字には気づかなかった。'],
  ['on the dot', 'a', 'at exactly the stated time', '（時間）ちょうどに、きっかり', 'The meeting starts at 9 on the dot.', '会議は9時きっかりに始まる。'],
  ['bring sth up', 'v', 'mention sth as a topic of conversation', '（話題を）持ち出す', "I'll bring it up at the next meeting.", '次の会議でその件を持ち出すよ。'],
  ['pricey', 'a', 'expensive', '値段が高い', 'That restaurant is nice but a bit pricey.', 'あのレストランはいいけど、ちょっと高い。'],
  ['touchy subject', 'n', 'topic that may upset or offend people', '触れにくい話題、デリケートな話題', 'Salary is a touchy subject in our office.', 'うちの職場では給料は触れにくい話題だ。'],
  ['one-off', 'a', 'happening only once', '一回限りの', 'This is a one-off payment, not a subscription.', 'これはサブスクではなく一回限りの支払いです。'],
  ['bug sb', 'v', 'annoy or bother sb', '（人を）いらいらさせる、困らせる', 'It really bugs me when people are late.', '人が遅刻すると本当にいらいらする。', 'annoy'],
  ['rusty', 'a', 'less skilled than before because of lack of practice', '（しばらくやらずに）腕がなまった', 'My French is a bit rusty.', '私のフランス語は少しなまっている。'],
  ['bright and early', 'a', 'very early in the morning', '朝早くに', "I'll see you bright and early tomorrow.", 'じゃあ明日の朝早くに。'],
  ['give sb a buzz', 'v', 'phone sb', '（人に）電話する', 'Give me a buzz when you arrive.', '着いたら電話して。'],
  ['work on sth', 'v', 'spend effort improving or developing sth', '～に取り組む、改善に努める', 'I need to work on my presentation skills.', 'プレゼンのスキルを磨かないといけない。'],
  ['in-your-face', 'a', 'aggressively bold and confrontational', '露骨な、挑発的な、押しつけがましい', 'Their marketing is very in-your-face.', '彼らのマーケティングはかなり押しが強い。'],
  ['come clean', 'v', 'confess the whole truth', '白状する、真実を打ち明ける', 'He finally came clean about the mistake.', '彼はついにミスについて白状した。', 'honest'],
  ['downer', 'n', 'something or someone that makes you feel low', '気が滅入るもの・人', 'The rainy weekend was a real downer.', '雨の週末は本当に気が滅入った。', 'sad'],
  ['packed', 'a', 'extremely crowded', 'ぎゅうぎゅう詰めの、満員の', 'The train was packed this morning.', '今朝の電車は満員だった。'],

  ['bail sb out', 'v', 'rescue sb from a difficult situation', '（人を）窮地から救う', 'Thanks for bailing me out yesterday.', '昨日は助けてくれてありがとう。'],
  ["get one's head around sth", 'v', 'manage to understand sth complicated', '（難しいことを）理解する', "I can't get my head around this new tax system.", 'この新しい税制がどうにも理解できない。', 'understand'],
  ['cut to the chase', 'v', 'get straight to the main point', '本題に入る、要点を言う', "Let me cut to the chase: we're over budget.", '単刀直入に言うと、予算オーバーだ。'],
  ['flag sth', 'v', 'draw attention to sth, often a problem', '（問題などを）指摘する、知らせる', 'Please flag any issues before Friday.', '問題があれば金曜までに知らせてください。'],
  ['old-school', 'a', 'traditional or old-fashioned', '昔ながらの、古風な', "He's old-school and still prints his emails.", '彼は昔気質で、いまだにメールを印刷する。', 'old'],
  ["get one's hopes up", 'v', 'become excited that sth good might happen', '期待を膨らませる', "Don't get your hopes up — it's not confirmed yet.", 'あまり期待しすぎないで。まだ確定じゃないから。'],
  ["behind sb's back", 'a', 'without sb knowing', '（人の）陰で、こっそり', 'She was criticizing him behind his back.', '彼女は陰で彼を批判していた。', 'secretly'],
  ['get back to sb', 'v', 'contact sb again later, usually with an answer', '（人に）折り返し連絡する', "I'll get back to you by tomorrow.", '明日までに折り返しご連絡します。'],
  ['freak (sb) out', 'v', '(make sb) panic or become very upset', 'パニックになる、（人を）ひどく動揺させる', 'The strange noise freaked me out.', 'その変な音にすごくびびった。'],
  ['put sth together', 'v', 'assemble or prepare sth', '～を組み立てる、まとめる', 'Can you put together a quick slide deck?', '簡単なスライドをまとめてもらえる？'],
  ['sounds like a plan', 'x', 'that seems like a good idea', 'いいね、そうしよう', 'Meet at 7? Sounds like a plan.', '7時に集合？いいね、そうしよう。'],
  ['drop sth/sb off', 'v', 'take sth/sb somewhere and leave them there', '（人・物を）送り届ける、置いていく', "I'll drop you off at the station.", '駅まで送っていくよ。'],
  ['attention to detail', 'n', 'care and accuracy about small things', '細部への気配り、几帳面さ', 'This job requires great attention to detail.', 'この仕事には細部への細やかな注意が必要だ。'],
  ['sick of', 'a', 'tired of and annoyed by sth', '～にうんざりして', "I'm sick of these endless meetings.", '終わりのない会議にはうんざりだ。'],
  ['white noise', 'n', 'irrelevant information that distracts from what matters', '（どうでもいい）雑音、無意味な情報', 'Most of the comments are just white noise.', 'コメントのほとんどはただの雑音だ。'],
  ['tricky', 'a', 'difficult and needing careful handling', '扱いが難しい、厄介な', 'Migrating the database will be tricky.', 'データベースの移行は厄介だろう。', 'difficult'],
  ['slammed', 'a', 'extremely busy', 'めちゃくちゃ忙しい', "I'm slammed this week; can we talk Monday?", '今週はめちゃくちゃ忙しいから、月曜に話せる？'],
  ['in a rush', 'a', 'in a hurry', '急いで', "Sorry, I'm in a rush — talk later.", 'ごめん、急いでるからまた後で。', 'hurry'],
  ['nice-to-have', 'n', 'something good to have but not essential', 'あれば嬉しいが必須ではないもの', 'Dark mode is a nice-to-have, not a must-have.', 'ダークモードはあれば嬉しい程度で、必須ではない。'],
  ['tell me about it', 'x', 'I completely agree (I have the same experience)', '本当にそうだよね、まったくだ', '“This traffic is awful.” “Tell me about it.”', '「この渋滞ひどいね」「ほんとそれ」'],
  ['take it easy', 'v', 'relax and avoid stress', '気楽にする、無理しない', "Take it easy this weekend — you've earned it.", '今週末はゆっくりして。頑張ったんだから。', 'relax'],
  ['wing it', 'v', 'do sth without any preparation', 'ぶっつけ本番でやる', "I didn't prepare slides, so I'll just wing it.", 'スライドを用意してないから、ぶっつけ本番でいくよ。', 'improvise'],
  ['turn sth/sb down', 'v', 'refuse an offer or reject a person', '（申し出・人を）断る', 'She turned down the job offer.', '彼女はその仕事のオファーを断った。'],
  ["keep one's cool", 'v', 'stay calm under pressure', '冷静さを保つ', 'He kept his cool even when the demo crashed.', 'デモが落ちても彼は冷静さを保っていた。', 'calm'],
  ['sort of/kind of', 'x', 'to some extent, but not completely', 'なんとなく、ちょっと、まあ', 'I sort of understand, but not really.', 'なんとなくはわかるけど、ちゃんとはわかってない。'],
  ['fill in for sb', 'v', "temporarily do sb's job", '（人の）代わりを務める', "Can you fill in for me at tomorrow's meeting?", '明日の会議、私の代わりに出てもらえる？'],
  ['help sb out', 'v', 'give sb assistance', '（人を）手伝う、助ける', 'Thanks for helping me out with the move.', '引っ越しを手伝ってくれてありがとう。'],
  ['make sure (that)', 'v', 'take action so that sth definitely happens or is true', '必ず～するようにする、確実にする', 'Make sure you save your work.', '作業内容は必ず保存しておいて。', 'check'],
  ["keep one's voice down", 'v', 'speak more quietly', '声を落とす、静かに話す', 'Keep your voice down — people are working.', '声を落として。みんな仕事中だから。'],
  ['FYI', 'x', 'just so you know; for your information', 'ご参考までに、念のため', 'FYI, the office is closed on Monday.', '念のため、月曜はオフィス休みです。'],
  ['chill', 'a', '(slang) relaxed and easygoing', '（スラング）落ち着いた、ゆるい', 'Our manager is pretty chill about remote work.', 'うちのマネージャーはリモートワークにかなり寛容だ。', 'relax'],
  ['bite the bullet', 'v', 'make yourself do sth unpleasant but necessary', '嫌なことを覚悟してやる', 'I finally bit the bullet and went to the dentist.', 'ついに覚悟を決めて歯医者に行った。'],
  ['look forward to sth', 'v', 'feel excited about sth that is going to happen', '～を楽しみにする', "I'm looking forward to working with you.", 'ご一緒できるのを楽しみにしています。'],
  ['on the same page', 'a', 'sharing the same understanding', '認識が一致して', "Let's make sure we're all on the same page.", '全員の認識が一致しているか確認しよう。'],
  ['clear sth up', 'v', 'make sth easier to understand; resolve confusion', '（誤解・疑問を）解く、はっきりさせる', 'Thanks for clearing up the confusion.', '混乱を解消してくれてありがとう。'],
  ['shattered', 'a', 'deeply upset or disappointed; (UK) exhausted', 'ひどく落ち込んだ；（英）くたくたの', "She was shattered when she didn't get the job.", '採用されず、彼女はひどく打ちのめされた。', 'sad'],
  ['give credit', 'v', "acknowledge or praise sb's work", '（人の功績を）認める、評価する', 'I have to give her credit — she handled it well.', '彼女の功績は認めないと。うまく対処した。', 'praise'],
  ['close enough', 'x', 'not exact, but acceptable', 'だいたい合ってる、まあ十分', "It's 4:58, but close enough — let's start.", '4時58分だけど、まあいいや、始めよう。'],
  ['lock sth down', 'v', 'finalize or secure sth', '～を確定させる、固める', 'We need to lock down the budget this week.', '今週中に予算を確定させる必要がある。', 'finish'],
  ['deal-breaker', 'n', 'an issue that makes an agreement or relationship fail', '決裂の原因となる条件、譲れない点', 'No remote work is a deal-breaker for me.', 'リモート不可なら、私にとっては受けられない条件だ。'],
  ['loaded', 'a', '(informal) very rich', '（口語）大金持ちの', 'His family is loaded.', '彼の家は大金持ちだ。', 'rich'],
  ['double-check sth/(that)', 'v', 'check sth again to be certain', '再確認する', 'Please double-check the numbers before sending.', '送る前に数字を再確認してください。', 'check'],
  ['cutting-edge', 'a', 'the most advanced or newest', '最先端の', 'They use cutting-edge AI technology.', '彼らは最先端のAI技術を使っている。'],
  ['go in circles', 'v', 'keep discussing sth without making progress', '堂々巡りする', "We're going in circles — let's decide.", '堂々巡りだ。決めてしまおう。', 'stuck'],
  ['chill out', 'v', 'calm down and relax', '落ち着く、リラックスする', "Chill out — it's just a minor bug.", '落ち着いて、ただの小さなバグだよ。', 'relax'],
  ['break for lunch', 'v', 'stop working in order to have lunch', '昼休みにする', "Let's break for lunch and continue at one.", '昼休みにして、1時から再開しよう。'],
  ['roughly', 'a', 'approximately', 'おおよそ、だいたい', 'The trip takes roughly three hours.', '移動にはだいたい3時間かかる。', 'approx'],
  ['stretch', 'n', 'an exaggeration; sth hard to believe', '誇張、言い過ぎ', 'Calling it a success is a bit of a stretch.', 'それを成功と呼ぶのはちょっと言い過ぎだ。'],
  ['on the right track', 'a', 'progressing in the right direction', '順調に進んで、正しい方向に向かって', 'Your solution is on the right track.', '君の解決策は正しい方向に向かっているよ。'],
  ["get one's hands on sth", 'v', 'manage to obtain sth', '～を手に入れる', 'I finally got my hands on the new iPhone.', 'やっと新しいiPhoneを手に入れた。', 'obtain'],
];
